### PR TITLE
libpiksi updates

### PR DESCRIPTION
**Pull request by jacobmcnamee**
- Update `libpiksi` directory structure with separate include folder
- Add `cmake` support to `libpiksi`
- Update `sbp_rtcm3_bridge` to use `libpiksi`

TODO:
- [ ] Test

/cc @swift-nav/firmware

### CODE REVIEW

**Comment by jacobmcnamee** [comment]
SBP callbacks may be registered via `sbp_callback_register()` declared in the local `sbp.h`.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-23-g4b88d79
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-23-g4b88d79/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-23-g4b88d79/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-23-g4b88d79

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-24-gc5eaf4d
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-24-gc5eaf4d/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-24-gc5eaf4d/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-24-gc5eaf4d

**Comment by anth-cole** [comment]
lgtm

**Pull request merged**
