### PR TITLE
upgrade buildroot to 2017.02.10

### PR DESCRIPTION
**Pull request by jck**
This is a bugfix release which fixes some issues including build issues in modern linux distros.

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.3.0-develop-2018020720-5-g3935457
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018020720-5-g3935457/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.3.0-develop-2018020720-5-g3935457/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018020720-5-g3935457

**Comment by silverjam** [comment]
Does this introduce any changes in package versions?

**Comment by jck** [comment]
upgraded to `2017.02.10`

looking at `buildroot/CHANGES`, it looks like the upgraded packages which affect us are `openssh`, `busybox` and the linaro toolchain. I'll schedule some HITL tests after the build is done.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.4.0-develop-2018032320-4-gb855185
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.4.0-develop-2018032320-4-gb855185/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.4.0-develop-2018032320-4-gb855185/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.4.0-develop-2018032320-4-gb855185

**Comment by silverjam** [comment]
Closing since we upgraded to 2018.02 instead

**Pull request closed without merging**
