### PR TITLE
Change to make TFTP boot from Scar work.

### PR DESCRIPTION
**Pull request by kmdade**
On my machine at least...

### CODE REVIEW

**Comment by silverjam** [comment]
Does this break booting with TFTP from a developer machine?

**Comment by silverjam** [comment]
HITL uses devboot, so kicked Travis (which will eventually schedule a HITL run) so we can see what happens.

**Comment by mfine** [comment]
Yeah, I think that was deliberate and remember some issues we ran into back in the day - may not impact some tftpd servers, may impact others. Now that I think about it, I think this might be a perf thing - the default is 512 or something - and takes forever to boot unless a bigger block size is chosen. That sounds familiar... Can we use a different tftp server on scar?

**Comment by kmdade** [comment]
Hey, so can confirm the default is 512 which is way small. I played around with the block size a lot trying to figure out why this was a problem for me. Basically if i set `-b 31964` no problem, but `-b 31965` times out. I actually didn't notice any discernible hit to the TFTP transfer time with any block size (even the default), but probably better to keep it as big as possible. Maybe we can use `-b 16384` and just call it good?

**Comment by kmdade** [comment]
Woops, didn't mean to click close, sorry!

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v1.4.0-develop-2018042018-23-g9258f7a
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=507641)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v1.4.0-develop-2018042018-23-g9258f7a&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v1.4.0-develop-2018042018-23-g9258f7a&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v1.4.0-develop-2018042018-23-g9258f7a
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v1.4.0-develop-2018042018-23-g9258f7a)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.4.0-develop-2018042018-23-g9258f7a/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.4.0-develop-2018042018-23-g9258f7a

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v1.4.0-develop-2018042018-23-g9258f7a
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=507658)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v1.4.0-develop-2018042018-23-g9258f7a&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v1.4.0-develop-2018042018-23-g9258f7a&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v1.4.0-develop-2018042018-23-g9258f7a
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v1.4.0-develop-2018042018-23-g9258f7a)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.4.0-develop-2018042018-23-g9258f7a/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.4.0-develop-2018042018-23-g9258f7a

**Comment by mfine** [comment]
Can you run this through rent-a-piksi in hitl and compare the before and after around the boot? 16K sounds find if there's no impact on perf. I remember we were seeing slow boots against some servers - can't remember which. Would be good to ensure it doesn't bog down hitl.

/cc @axlan

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v1.4.0-develop-2018042720-4-gc2ce1ea
There was an error using the HITL API to kick off smoke tests for this commit. See https://travis-ci.org/swift-nav/piksi_buildroot/builds/373150174.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.4.0-develop-2018042720-4-gc2ce1ea
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v1.4.0-develop-2018042720-4-gc2ce1ea)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.4.0-develop-2018042720-4-gc2ce1ea/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.4.0-develop-2018042720-4-gc2ce1ea

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v1.4.0-develop-2018042720-9-g21164bc
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=513971)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v1.4.0-develop-2018042720-9-g21164bc&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v1.4.0-develop-2018042720-9-g21164bc&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v1.4.0-develop-2018042720-9-g21164bc
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v1.4.0-develop-2018042720-9-g21164bc)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.4.0-develop-2018042720-9-g21164bc/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.4.0-develop-2018042720-9-g21164bc

**Comment by kmdade** [comment]
@jdiamond @silverjam can I merge this?

**Comment by axlan** [comment]
I'm kicked off some runs in HITL to see if there's any major change in startup time https://gnss-analysis.swiftnav.com/jobs/id=572639 if there isn't a significant impact it LGTM

**Comment by axlan** [comment]
Looks like this speeds things up if anything.

**Comment by kmdade** [comment]
ayyyy! Thanks everybody, looking forward to having tftpboot on my desk piksis! :)

**Pull request merged**
