### PR TITLE
Remove orion daemon from release [ESD-809]

### PR DESCRIPTION
**Pull request by mfine**
Don't think we want orion daemon coming into the release. For the release build, believe this should be what's needed to keep the orion daemon out?

### CODE REVIEW

**Comment by mfine** [comment]
Size drops:

```
➜  ~ aws s3 ls --recursive s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.0.0-develop-2018102218-16-gc36594e9/v3/prod/                                                
2018-10-29 23:24:23    4563787 piksi_buildroot/v2.0.0-develop-2018102218-16-gc36594e9/v3/prod/PiksiMulti-DEV-v2.0.0-develop-2018102218-16.bin
2018-10-29 23:24:24     516071 piksi_buildroot/v2.0.0-develop-2018102218-16-gc36594e9/v3/prod/PiksiMulti-FAILSAFE-v2.0.0-develop-2018102218-16.bin
2018-10-29 23:24:25   18952170 piksi_buildroot/v2.0.0-develop-2018102218-16-gc36594e9/v3/prod/PiksiMulti-INTERNAL-v2.0.0-develop-2018102218-16.bin
2018-10-29 23:26:15   16928098 piksi_buildroot/v2.0.0-develop-2018102218-16-gc36594e9/v3/prod/PiksiMulti-UNPROTECTED-v2.0.0-develop-2018102218-16.bin
2018-10-29 23:26:13   18420186 piksi_buildroot/v2.0.0-develop-2018102218-16-gc36594e9/v3/prod/PiksiMulti-v2.0.0-develop-2018102218-16.bin
2018-10-29 23:24:22       8035 piksi_buildroot/v2.0.0-develop-2018102218-16-gc36594e9/v3/prod/boot.bin
2018-10-29 22:45:19        292 piksi_buildroot/v2.0.0-develop-2018102218-16-gc36594e9/v3/prod/build_docker.out
2018-10-29 23:13:39    4708412 piksi_buildroot/v2.0.0-develop-2018102218-16-gc36594e9/v3/prod/build_host.out
2018-10-29 23:24:21    5867685 piksi_buildroot/v2.0.0-develop-2018102218-16-gc36594e9/v3/prod/build_internal.out
2018-10-29 23:26:12    7567760 piksi_buildroot/v2.0.0-develop-2018102218-16-gc36594e9/v3/prod/build_release.out
2018-10-29 23:28:55    6478069 piksi_buildroot/v2.0.0-develop-2018102218-16-gc36594e9/v3/prod/build_sdk.out
2018-10-29 23:24:27   18653711 piksi_buildroot/v2.0.0-develop-2018102218-16-gc36594e9/v3/prod/uImage.piksiv3_prod
```

```
➜  ~ aws s3 ls --recursive s3://swiftnav-artifacts/piksi_buildroot/v2.0.0-develop-2018102218/v3/prod/ 
2018-10-22 15:29:05    4563787 piksi_buildroot/v2.0.0-develop-2018102218/v3/prod/PiksiMulti-DEV-v2.0.0-develop-2018102218.bin
2018-10-22 15:29:06     516071 piksi_buildroot/v2.0.0-develop-2018102218/v3/prod/PiksiMulti-FAILSAFE-v2.0.0-develop-2018102218.bin
2018-10-22 15:29:07   21447098 piksi_buildroot/v2.0.0-develop-2018102218/v3/prod/PiksiMulti-INTERNAL-v2.0.0-develop-2018102218.bin
2018-10-22 15:30:58   19997242 piksi_buildroot/v2.0.0-develop-2018102218/v3/prod/PiksiMulti-UNPROTECTED-v2.0.0-develop-2018102218.bin
2018-10-22 15:30:56   21525754 piksi_buildroot/v2.0.0-develop-2018102218/v3/prod/PiksiMulti-v2.0.0-develop-2018102218.bin
2018-10-22 15:29:04       8035 piksi_buildroot/v2.0.0-develop-2018102218/v3/prod/boot.bin
2018-10-22 14:27:41        124 piksi_buildroot/v2.0.0-develop-2018102218/v3/prod/build_docker.out
2018-10-22 15:07:33    5334308 piksi_buildroot/v2.0.0-develop-2018102218/v3/prod/build_host.out
2018-10-22 15:29:03    6055563 piksi_buildroot/v2.0.0-develop-2018102218/v3/prod/build_internal.out
2018-10-22 15:30:54    8340200 piksi_buildroot/v2.0.0-develop-2018102218/v3/prod/build_release.out
2018-10-22 15:48:34    6694893 piksi_buildroot/v2.0.0-develop-2018102218/v3/prod/build_sdk.out
2018-10-22 15:48:36  273092360 piksi_buildroot/v2.0.0-develop-2018102218/v3/prod/piksi_sdk.txz
2018-10-22 15:29:09   21148639 piksi_buildroot/v2.0.0-develop-2018102218/v3/prod/uImage.piksiv3_prod
```

**Comment by silverjam** [comment]
@mfine do you want to re-enable this after we branch?

**Comment by mfine** [comment]
Yeah, I'm not sure the best process here - disable before branching, re-enabling in master or disabling after branching.

**Comment by silverjam** [comment]
I think either makes sense. Feel free to merge.

**Comment by mfine** [comment]
I think so

**Comment by benjaminaltieri** [comment]
Should re-target to `v2.2.0-release` and merge, yes?

**Comment by mfine** [comment]
Rebased. Feel free to merge as necessary!

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.2.0-4-gc9e27cc2
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=766432)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.0-4-gc9e27cc2&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.0-4-gc9e27cc2&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.2.0-4-gc9e27cc2
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.2.0-4-gc9e27cc2)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.2.0-4-gc9e27cc2/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.2.0-4-gc9e27cc2

**Pull request merged**
