### PR TITLE
An ntrip daemon

### PR DESCRIPTION
**Pull request by mfine**
Similar to skylark daemon, but with ntrip. Uses libcurl.

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.8-3-g5bbb3f3
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.8-3-g5bbb3f3/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.8-3-g5bbb3f3/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.8-3-g5bbb3f3

**Comment by mfine** [comment]
Dumping this thread here:

the downloading works fine

I can download to a fifo and read out the fifo continously

when I hook it up to the adaper, I get problems

I think I did it right

`zmq_adapter -f rtcm3 --file /tmp/fifo -p >tcp://127.0.0.1:45031`

so the adapter runs for a bit, I get some observations in  (yay!)

and then it croaks

on the adapter i see it exit the io loop:

 ```opened socket: >tcp://127.0.0.1:45031
io loop begin
read 12 bytes
read 1 bytes
read 72 bytes
read 100 bytes
read 102 bytes
read 100 bytes
read 172 bytes
read 100 bytes
read 102 bytes
read 100 bytes
wrote 202 bytes
wrote 27 bytes
io loop end```

on the daemon side, I see the writes just up and fail:

 ```Apr 19 06:04:32 piksi user.debug ntrip_daemon: write bytes (1) 1
Apr 19 06:04:32 piksi user.debug ntrip_daemon: write bytes (72) 72
Apr 19 06:04:33 piksi user.debug ntrip_daemon: write bytes (100) 100
Apr 19 06:04:33 piksi user.debug ntrip_daemon: write bytes (102) 102
Apr 19 06:04:34 piksi user.debug ntrip_daemon: write bytes (100) 100
Apr 19 06:04:34 piksi user.debug ntrip_daemon: write bytes (172) 172
Apr 19 06:04:35 piksi user.debug ntrip_daemon: write bytes (100) 100
Apr 19 06:04:35 piksi user.debug ntrip_daemon: write bytes (102) 102
Apr 19 06:04:36 piksi user.debug ntrip_daemon: write bytes (100) 100
Apr 19 06:04:36 piksi user.debug ntrip_daemon: write bytes (172) -1
Apr 19 06:04:36 piksi user.debug ntrip_daemon: curl error (23) "Failed writing body (4294967295 != 172)"```

and the adapter seems to have closed the fifo!

or somethign because I get -1 writing to it always now

looking at the adapter, it’s almost like the framing is not happening because all I see are reads, no writes

but then I definitely got some obs in

am I doing this right?

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.8-11-g0e88de3
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.8-11-g0e88de3/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.8-11-g0e88de3/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.8-11-g0e88de3

**Comment by mfine** [comment]
Building. Going to bring in.

**Pull request merged**
