### PR TITLE
Add UART1 whitelist to TCP server/client and UDP client [release]

### PR DESCRIPTION
**Pull request by cbeighley**
For https://github.com/swift-nav/piksi_v3_bug_tracking/issues/992.

### CODE REVIEW

**Comment by mfine** [comment]
To add to the above - the whitelists only work on the way out of the device. In paths do not go through whitelists. Therefore, anything that is sending out can benefit from a whitelist (tcp server and client, udp client) while anything that is only receiving will not (udp server).

**Comment by cbeighley** [comment]
@mfine Per our discussion just now, I think I will just not worry about UDP for now, as it's not clear to me there is necessary an issue here. Adding TCP client sounds like a good idea.

**Comment by cbeighley** [comment]
Actually...yeah...let's do it on UDP client as well.

**Comment by mfine** [comment]
:shipit:

**Comment by anonymous-travis-swiftnav** [comment]
## v1.4.1-7-g9ca845e
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.4.1-7-g9ca845e/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.4.1-7-g9ca845e/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.4.1-7-g9ca845e

**Pull request merged**
