### PR TITLE
ESD-1180: Support NMEA GSV generation in gnss-converters

### PR DESCRIPTION
**Pull request by nsirola**
Pull in `gnss-converters` tagged branch including https://github.com/swift-nav/gnss-converters/pull/180 

Pending `libsbp` master tag to include https://github.com/swift-nav/libsbp/pull/670

NMEA output from the PR:
```
$GPZDA,113556.00,28,03,2019,,*60
$GPGSV,3,1,10,01,16,020,41,06,03,126,42,10,12,292,43,12,36,242,50*76
$GPGSV,3,2,10,13,03,174,39,15,20,202,48,17,49,076,48,19,54,118,48*71
$GPGSV,3,3,10,24,72,232,51,28,15,072,41*72
$GLGSV,3,1,09,67,14,232,43,68,37,288,48,69,23,344,46,76,26,098,45*60
$GLGSV,3,2,09,77,86,346,45,78,33,282,49,85,17,016,42,86,50,076,47*6A
$GLGSV,3,3,09,87,25,148,48*55
$GAGSV,2,1,07,301,06,090,36,303,30,308,44,305,31,248,44,324,66,254,49*6D
$GAGSV,2,2,07,325,13,266,43,326,27,040,43,331,55,098,47*6E
$GBGSV,3,1,09,408,35,076,42,413,28,104,43,414,23,288,43,421,08,242,42*6B
$GBGSV,3,2,09,426,29,282,46,427,13,030,38,429,34,152,47,430,45,080,48*66
$GBGSV,3,3,09,436,36,116,46*62
$GNGSA,A,3,01,10,12,15,17,19,24,28,,,,,1.1,0.6,0.9*26
$GNGSA,A,3,67,68,69,76,77,78,85,86,87,,,,1.1,0.6,0.9*21
$GNGSA,A,3,303,305,324,325,326,331,,,,,,,1.1,0.6,0.9*22
$GNGSA,A,3,408,413,414,426,427,429,430,436,,,,,1.1,0.6,0.9*20
$GPRMC,113556.00,A,6126.8181226,N,02351.5084646,E,0.01,,280319,,,D*4D
$GPVTG,,T,,M,0.01,N,0.03,K,D*24
$GPGLL,6126.8181226,N,02351.5084646,E,113556.00,A,D*64
$GNGST,113556.00,28,03,2019,,,0.523972,0.505040,-0.297619,0.522370,0.506696,1.086517*45
$GPGGA,113556.00,6126.8181226,N,02351.5084646,E,2,22,0.6,185.01,M,0.0,M,,*6C
$GPVTG,,T,,M,0.01,N,0.01,K,D*26
$GNGST,113556.20,28,03,2019,,,0.523972,0.505040,-0.297623,0.522371,0.506696,1.086518*40
$GPGGA,113556.20,6126.8181220,N,02351.5084748,E,2,22,0.6,185.02,M,0.0,M,,*64
$GPVTG,,T,,M,0.01,N,0.02,K,D*25
$GNGST,113556.40,28,03,2019,,,0.523973,0.505040,-0.297627,0.522372,0.506696,1.086519*41
$GPGGA,113556.40,6126.8181220,N,02351.5084820,E,2,22,0.6,185.02,M,0.0,M,,*63
$GPVTG,,T,,M,0.01,N,0.02,K,D*25
$GNGST,113556.60,28,03,2019,,,0.523974,0.505040,-0.297625,0.522372,0.506696,1.086519*46
$GPGGA,113556.60,6126.8181214,N,02351.5084892,E,2,22,0.6,185.02,M,0.0,M,,*6F
$GPVTG,,T,,M,0.01,N,0.01,K,D*26
$GNGST,113556.80,28,03,2019,,,0.523974,0.505041,-0.297636,0.522373,0.506697,1.086520*41
$GPGGA,113556.80,6126.8181214,N,02351.5084952,E,2,22,0.6,185.02,M,0.0,M,,*6C
$GPVTG,,T,,M,0.00,N,0.01,K,D*27
$GNGST,113557.00,28,03,2019,,,0.523975,0.505040,-0.297627,0.522373,0.506697,1.086521*49
$GPGGA,113557.00,6126.8181208,N,02351.5085024,E,2,22,0.6,185.03,M,0.0,M,,*60
$GPVTG,,T,,M,0.00,N,0.01,K,D*27
$GNGST,113557.20,28,03,2019,,,0.523975,0.505041,-0.297644,0.522374,0.506697,1.086522*4B
$GPGGA,113557.20,6126.8181202,N,02351.5085078,E,2,22,0.6,185.03,M,0.0,M,,*61
$GPVTG,,T,,M,0.01,N,0.02,K,D*25
$GNGST,113557.40,28,03,2019,,,0.523976,0.505041,-0.297641,0.522375,0.506697,1.086523*4B
$GPGGA,113557.40,6126.8181196,N,02351.5085168,E,2,22,0.6,185.03,M,0.0,M,,*69
$GPVTG,,T,,M,0.01,N,0.01,K,D*26
$GNGST,113557.60,28,03,2019,,,0.523977,0.505041,-0.297645,0.522375,0.506697,1.086523*4C
$GPGGA,113557.60,6126.8181184,N,02351.5085228,E,2,22,0.6,185.03,M,0.0,M,,*6F
$GPVTG,,T,,M,0.01,N,0.02,K,D*25
$GNGST,113557.80,28,03,2019,,,0.523977,0.505042,-0.297656,0.522376,0.506697,1.086524*47
$GPGGA,113557.80,6126.8181184,N,02351.5085294,E,2,22,0.6,185.03,M,0.0,M,,*66
```

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.1.0-develop-2019032221-8-gde3055c1

These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.

### job status
+ [live-roof-650-townsend runs](https://gnss-analysis.swiftnav.com/jobs/id=972343)
+ [live-roof-650-townsend-dropouts-zero-baseline runs](https://gnss-analysis.swiftnav.com/jobs/id=972344)

### gnss-analysis results
At least one run must complete for these links to have data.

#### passfail
+ [live-roof-650-townsend](https://gnss-analysis.swiftnav.com/metrics_preset=pass_fail&scenario=live-roof-650-townsend&summary_type=q50&groupby_key=firmware&firmware_versions=v2.1.0-develop-2019032221-8-gde3055c1&build_type=buildroot_pr&display_type=table)
+ [live-roof-650-townsend-dropouts-zero-baseline](https://gnss-analysis.swiftnav.com/metrics_preset=pass_fail&scenario=live-roof-650-townsend-dropouts-zero-baseline&summary_type=q50&groupby_key=firmware&firmware_versions=v2.1.0-develop-2019032221-8-gde3055c1&build_type=buildroot_pr&display_type=table)

#### detailed
+ [live-roof-650-townsend](https://gnss-analysis.swiftnav.com/metrics_preset=detailed&scenario=live-roof-650-townsend&summary_type=q50&groupby_key=firmware&firmware_versions=v2.1.0-develop-2019032221-8-gde3055c1&build_type=buildroot_pr&display_type=table)
+ [live-roof-650-townsend-dropouts-zero-baseline](https://gnss-analysis.swiftnav.com/metrics_preset=detailed&scenario=live-roof-650-townsend-dropouts-zero-baseline&summary_type=q50&groupby_key=firmware&firmware_versions=v2.1.0-develop-2019032221-8-gde3055c1&build_type=buildroot_pr&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.1.0-develop-2019032221-8-gde3055c1
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.1.0-develop-2019032221-8-gde3055c1)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.1.0-develop-2019032221-8-gde3055c1/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.1.0-develop-2019032221-8-gde3055c1

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.1.0-develop-2019032221-18-g7a72804f

These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.

### job status
+ [live-roof-650-townsend runs](https://gnss-analysis.swiftnav.com/jobs/id=974286)
+ [live-roof-650-townsend-dropouts-zero-baseline runs](https://gnss-analysis.swiftnav.com/jobs/id=974287)

### gnss-analysis results
At least one run must complete for these links to have data.

#### passfail
+ [live-roof-650-townsend](https://gnss-analysis.swiftnav.com/metrics_preset=pass_fail&scenario=live-roof-650-townsend&summary_type=q50&groupby_key=firmware&firmware_versions=v2.1.0-develop-2019032221-18-g7a72804f&build_type=buildroot_pr&display_type=table)
+ [live-roof-650-townsend-dropouts-zero-baseline](https://gnss-analysis.swiftnav.com/metrics_preset=pass_fail&scenario=live-roof-650-townsend-dropouts-zero-baseline&summary_type=q50&groupby_key=firmware&firmware_versions=v2.1.0-develop-2019032221-18-g7a72804f&build_type=buildroot_pr&display_type=table)

#### detailed
+ [live-roof-650-townsend](https://gnss-analysis.swiftnav.com/metrics_preset=detailed&scenario=live-roof-650-townsend&summary_type=q50&groupby_key=firmware&firmware_versions=v2.1.0-develop-2019032221-18-g7a72804f&build_type=buildroot_pr&display_type=table)
+ [live-roof-650-townsend-dropouts-zero-baseline](https://gnss-analysis.swiftnav.com/metrics_preset=detailed&scenario=live-roof-650-townsend-dropouts-zero-baseline&summary_type=q50&groupby_key=firmware&firmware_versions=v2.1.0-develop-2019032221-18-g7a72804f&build_type=buildroot_pr&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.1.0-develop-2019032221-18-g7a72804f
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.1.0-develop-2019032221-18-g7a72804f)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.1.0-develop-2019032221-18-g7a72804f/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.1.0-develop-2019032221-18-g7a72804f

**Comment by nsirola** [comment]
This just misses the final tagged branch of `libsbp` now

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.1.0-develop-2019032221-19-ga6acf4e6

These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.

### job status
+ [live-roof-650-townsend runs](https://gnss-analysis.swiftnav.com/jobs/id=974382)
+ [live-roof-650-townsend-dropouts-zero-baseline runs](https://gnss-analysis.swiftnav.com/jobs/id=974383)

### gnss-analysis results
At least one run must complete for these links to have data.

#### passfail
+ [live-roof-650-townsend](https://gnss-analysis.swiftnav.com/metrics_preset=pass_fail&scenario=live-roof-650-townsend&summary_type=q50&groupby_key=firmware&firmware_versions=v2.1.0-develop-2019032221-19-ga6acf4e6&build_type=buildroot_pr&display_type=table)
+ [live-roof-650-townsend-dropouts-zero-baseline](https://gnss-analysis.swiftnav.com/metrics_preset=pass_fail&scenario=live-roof-650-townsend-dropouts-zero-baseline&summary_type=q50&groupby_key=firmware&firmware_versions=v2.1.0-develop-2019032221-19-ga6acf4e6&build_type=buildroot_pr&display_type=table)

#### detailed
+ [live-roof-650-townsend](https://gnss-analysis.swiftnav.com/metrics_preset=detailed&scenario=live-roof-650-townsend&summary_type=q50&groupby_key=firmware&firmware_versions=v2.1.0-develop-2019032221-19-ga6acf4e6&build_type=buildroot_pr&display_type=table)
+ [live-roof-650-townsend-dropouts-zero-baseline](https://gnss-analysis.swiftnav.com/metrics_preset=detailed&scenario=live-roof-650-townsend-dropouts-zero-baseline&summary_type=q50&groupby_key=firmware&firmware_versions=v2.1.0-develop-2019032221-19-ga6acf4e6&build_type=buildroot_pr&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.1.0-develop-2019032221-19-ga6acf4e6
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.1.0-develop-2019032221-19-ga6acf4e6)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.1.0-develop-2019032221-19-ga6acf4e6/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.1.0-develop-2019032221-19-ga6acf4e6

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.1.0-develop-2019032221-20-g6d31bb93

These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.

### job status
+ [live-roof-650-townsend runs](https://gnss-analysis.swiftnav.com/jobs/id=974628)
+ [live-roof-650-townsend-dropouts-zero-baseline runs](https://gnss-analysis.swiftnav.com/jobs/id=974629)

### gnss-analysis results
At least one run must complete for these links to have data.

#### passfail
+ [live-roof-650-townsend](https://gnss-analysis.swiftnav.com/metrics_preset=pass_fail&scenario=live-roof-650-townsend&summary_type=q50&groupby_key=firmware&firmware_versions=v2.1.0-develop-2019032221-20-g6d31bb93&build_type=buildroot_pr&display_type=table)
+ [live-roof-650-townsend-dropouts-zero-baseline](https://gnss-analysis.swiftnav.com/metrics_preset=pass_fail&scenario=live-roof-650-townsend-dropouts-zero-baseline&summary_type=q50&groupby_key=firmware&firmware_versions=v2.1.0-develop-2019032221-20-g6d31bb93&build_type=buildroot_pr&display_type=table)

#### detailed
+ [live-roof-650-townsend](https://gnss-analysis.swiftnav.com/metrics_preset=detailed&scenario=live-roof-650-townsend&summary_type=q50&groupby_key=firmware&firmware_versions=v2.1.0-develop-2019032221-20-g6d31bb93&build_type=buildroot_pr&display_type=table)
+ [live-roof-650-townsend-dropouts-zero-baseline](https://gnss-analysis.swiftnav.com/metrics_preset=detailed&scenario=live-roof-650-townsend-dropouts-zero-baseline&summary_type=q50&groupby_key=firmware&firmware_versions=v2.1.0-develop-2019032221-20-g6d31bb93&build_type=buildroot_pr&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.1.0-develop-2019032221-20-g6d31bb93
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.1.0-develop-2019032221-20-g6d31bb93)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.1.0-develop-2019032221-20-g6d31bb93/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.1.0-develop-2019032221-20-g6d31bb93

**Pull request merged**
