### PR TITLE
Stop piksi_multitool helper commands if they're already running

### PR DESCRIPTION
**Pull request by silverjam**

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.0.0-develop-2018102218-9-g0b129d50
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=737702)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.0.0-develop-2018102218-9-g0b129d50&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.0.0-develop-2018102218-9-g0b129d50&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.0.0-develop-2018102218-9-g0b129d50
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.0.0-develop-2018102218-9-g0b129d50)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.0.0-develop-2018102218-9-g0b129d50/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.0.0-develop-2018102218-9-g0b129d50

**Review by benjaminaltieri — APPROVED** [review]
🛴

**Comment by silverjam** [comment]
This doesn't actually work 😭

**Comment by benjaminaltieri** [comment]
Hmm, seemed to work for me.. the pid of the helper script process changes when I relaunch the tool, but I'm not sure that's what you were really after.. I was having a separate issue where grabbing the syslog would get corrupted after running the log streaming command. Maybe putting those in different ports might help?

**Comment by silverjam** [comment]
Would need to see the issue you're having to understand better.  However, I was seeing that it wasn't recording the PIDs successfully because the processes couldn't directly access the `/var/run` directory (because they're started as the `piksi_sys` user), when I fixed that it would record PIDs, but not the PIDs that were actually holding the socket open.  It looks like `nc` is able to open a port, then exec into a command (with the `-e` switch) and have this process write to the socket it opens without `nc` itself remaining resident, so I'm not sure what's happening with the PIDs in this case-- regardless, we're not grabbing a PID that's useful, since it's usually something that's already exited, so looking for and killing that PID isn't useful (we could scrap ss output to find the PID, but I think this is really hacky).  I think we may want to switch to socat or something that can remain resident so we can stop/restart it if needed.

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.0.0-develop-2018102218-17-g80f39253
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=745225)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.0.0-develop-2018102218-17-g80f39253&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.0.0-develop-2018102218-17-g80f39253&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.0.0-develop-2018102218-17-g80f39253
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.0.0-develop-2018102218-17-g80f39253)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.0.0-develop-2018102218-17-g80f39253/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.0.0-develop-2018102218-17-g80f39253

**Pull request closed without merging**
