### PR TITLE
fixup repeat sbp_cmd_resp PR

### PR DESCRIPTION
**Pull request by denniszollo**
still awaiting testing in a real image.

### CODE REVIEW

**Comment by denniszollo** [comment]
This still doesn't work because the argument $1 in the single quotes isn't expanded

**Comment by denniszollo** [comment]
Tested and functional

**Comment by benjaminaltieri** [comment]
@denniszollo do we have a master PR for this?

**Comment by silverjam** [comment]
Did we port this to master yet? @denniszollo @benjaminaltieri ?

**Comment by benjaminaltieri** [comment]
yup - #769

**Pull request merged**
