### PR TITLE
update firmware pointer [TEST ONLY]

### PR DESCRIPTION
**Pull request by wilsonjt**

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017110820-5-g4ad4fbf
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-5-g4ad4fbf/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017110820-5-g4ad4fbf/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-5-g4ad4fbf

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017110820-6-gdefec19
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-6-gdefec19/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017110820-6-gdefec19/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-6-gdefec19

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017110820-7-g4f4f8a9
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-7-g4f4f8a9/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017110820-7-g4f4f8a9/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-7-g4f4f8a9

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017110820-8-gc3e974a
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-8-gc3e974a/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017110820-8-gc3e974a/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-8-gc3e974a

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017111721-8-gf7e73fc
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017111721-8-gf7e73fc/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017111721-8-gf7e73fc/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017111721-8-gf7e73fc

**Comment by wilsonjt** [comment]
This testing is complete, closing PR.

**Pull request closed without merging**
