### PR TITLE
Move RTCM decoder out of buildroot

### PR DESCRIPTION
**Pull request by anth-cole**
Move change the sbp_rtcm3_bridge package to just handle passing an rtcm3 buffer stream and returns back an sbp callback of the sbp message decoded.

The following packages were added

- librtcm - handles taking a buffer and decoding to an rtcm3 message struct
- gnss-convertors - passes a buffer to librtcm, converts the returned rtcm3 message struct to an sbp message type, and handles the logic of emitting the sbp messages.

@lbara Is someone from FW able to review this for me? In particular I'm not sure about using `depends on` rather than `select` in sbp_rtcm3_bridge Config.ini file, if I use `selects` it errors out I believe because of a circular dependency with libsbp although I'm not sure I fully understand the difference between the 2 keywords.

This is also currently pulling in a branch of gnss-convertors, once I merge those changes I'll update this PR before merging

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-216-gf030964
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-216-gf030964/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-216-gf030964/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-216-gf030964

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-develop-2017071417-9-gd2181f8
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017071417-9-gd2181f8/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-develop-2017071417-9-gd2181f8/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017071417-9-gd2181f8

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-develop-2017071417-10-g40e189c
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017071417-10-g40e189c/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-develop-2017071417-10-g40e189c/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017071417-10-g40e189c

**Comment by anth-cole** [comment]
I've benchtested this now and works with the latest update, get both glo and gps obs and fixes with the GPS obs.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-develop-2017071417-11-g4a7c9cb
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017071417-11-g4a7c9cb/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-develop-2017071417-11-g4a7c9cb/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017071417-11-g4a7c9cb

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-develop-2017071417-12-g5be2cb2
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017071417-12-g5be2cb2/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-develop-2017071417-12-g5be2cb2/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017071417-12-g5be2cb2

**Comment by axlan** [comment]
Seems like a good pattern for adding future packages. LGTM when the current include issue is fixed.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-develop-2017071417-18-gb402237
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017071417-18-gb402237/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-develop-2017071417-18-gb402237/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017071417-18-gb402237

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-develop-2017071417-7-g860dfc0
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017071417-7-g860dfc0/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-develop-2017071417-7-g860dfc0/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017071417-7-g860dfc0

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-develop-2017071417-9-g0850e19
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017071417-9-g0850e19/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-develop-2017071417-9-g0850e19/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017071417-9-g0850e19

**Pull request merged**
