### PR TITLE
Add picocom utility for modem diagnostics

### PR DESCRIPTION
**Pull request by silverjam**
Add the screen utility to facilitate debugging of cellular modem.

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017122003-2-g91c06da
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017122003-2-g91c06da/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017122003-2-g91c06da/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017122003-2-g91c06da

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017122003-2-g91c06da
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017122003-2-g91c06da/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017122003-2-g91c06da/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017122003-2-g91c06da

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017122916-3-g7bab9e0
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017122916-3-g7bab9e0/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017122916-3-g7bab9e0/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017122916-3-g7bab9e0

**Comment by silverjam** [comment]
Prebuilt copy of screen:

[screen.gz](https://github.com/swift-nav/piksi_buildroot/files/1604832/screen.gz)

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2018010520-3-g652f14c
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2018010520-3-g652f14c/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2018010520-3-g652f14c/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2018010520-3-g652f14c

**Comment by silverjam** [comment]
@srossel please give this build a try when you get a chance, it has a tool called [picoterm](https://linux.die.net/man/8/picocom) enabled that should allow us to easily send AT commands to the GSM modem while having a minimal impact on firmware image size (cc: @mbavaro).

**Comment by srossel** [comment]
Implementation has been tested.
In order to use picocom, please follow this steps:
1.- Disable cell-modem via Swift Console Settings.
2.- Connect to the device via ssh and run this command : "picocom -b 115200 /dev/ttyACM0"
3.- Type or paste AT command, you will see the response.
4.- Controle+A and then X to exit picocom.

Picocom will not accept any AT-Commands if Cell-modem is enabled.

Please, proceed to merge. 

Thank you very much,

Sergio

**Pull request merged**
