### PR TITLE
Turn off telnet/telnetd, fix make clean target

### PR DESCRIPTION
**Pull request by silverjam**
+ Turn off telnet and telnetd feature in busybox.

+ The clean target can't delete the directories in buildroot/output unless
  they are empty, so use rm -rf instead.

### CODE REVIEW

**Comment by lbara** [comment]
Thanks! Go ahead with this one, no brainer for me.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-develop-2017100621-19-g5d990fe
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017100621-19-g5d990fe/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-develop-2017100621-19-g5d990fe/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017100621-19-g5d990fe

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-develop-2017100621-20-ge5834d7
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017100621-20-ge5834d7/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-develop-2017100621-20-ge5834d7/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017100621-20-ge5834d7

**Comment by silverjam** [comment]
Quick verification that telnet was gone:

On piksi:
```
root@piksi:~ # ps|grep telnet
 1152 root       0:00 grep telnet
root@piksi:~ # telnet
-sh: telnet: not found
```

On host:
```
$ telnet piksi
Trying 10.1.22.222...
telnet: connect to address 10.1.22.222: Connection refused
telnet: Unable to connect to remote host
```

**Pull request merged**
