### PR TITLE
IP security reference design

### PR DESCRIPTION
**Pull request by silverjam**

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-branch-13-g49aeaf3
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-branch-13-g49aeaf3/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-branch-13-g49aeaf3/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-branch-13-g49aeaf3

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-branch-14-g0213e9d
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-branch-14-g0213e9d/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-branch-14-g0213e9d/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-branch-14-g0213e9d

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-branch-17-gf314cb8
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-branch-17-gf314cb8/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-branch-17-gf314cb8/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-branch-17-gf314cb8

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017110820-42-gd878832
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-42-gd878832/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017110820-42-gd878832/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-42-gd878832

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017110820-46-g2b7168b
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-46-g2b7168b/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017110820-46-g2b7168b/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-46-g2b7168b

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017110820-48-g6773d17
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-48-g6773d17/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017110820-48-g6773d17/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-48-g6773d17

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017111721-51-g6fed6b9
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017111721-51-g6fed6b9/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017111721-51-g6fed6b9/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017111721-51-g6fed6b9

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017111721-52-g6d667c3
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017111721-52-g6d667c3/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017111721-52-g6d667c3/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017111721-52-g6d667c3

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017111721-53-g041b4a8
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017111721-53-g041b4a8/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017111721-53-g041b4a8/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017111721-53-g041b4a8

**Comment by jck** [comment]
@silverjam This PR has merge conflicts.

**Comment by silverjam** [comment]
@jck some trivial conflicts with the LED changes, fixed

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017111721-66-gbfd836d
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017111721-66-gbfd836d/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017111721-66-gbfd836d/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017111721-66-gbfd836d

**Comment by silverjam** [comment]
Closed in favor of #393

**Pull request closed without merging**
