### PR TITLE
Add Monit and Stress packages

### PR DESCRIPTION
**Pull request by fnoble**
Monit can be used for process monitoring and much more. Moving some of our daemons over to being run by Monit will allow us to restart them easily if they die.

Stress is a simple tool to stress the CPU, we can use it for thermal testing.

cc: @jacobmcnamee

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## 439c332
+ [s3://swiftnav-artifacts-pull-requests/piksi_buildroot/439c332](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/439c332/)

**Comment by jacobmcnamee** [comment]
FYI defconfigs are autogenerated. I usually use
`make menuconfig`
(make changes)
`make savedefconfig`
and then you might have to copy the written file back to the original. I forget which of u-boot, buildroot, linux do that automatically.

**Comment by jacobmcnamee** [comment]
Use autogenerated defconfig and then lgtm

**Comment by anonymous-travis-swiftnav** [comment]
## aa8c8e3
+ [s3://swiftnav-artifacts-pull-requests/piksi_buildroot/aa8c8e3](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/aa8c8e3/)

**Pull request merged**
