### PR TITLE
Allow standalone logger to handle endpoint disconnects  [ESD-981] [ESD-988]

### PR DESCRIPTION
**Pull request by benjaminaltieri**
Related to #1096, this ports the reconnect logic from `sbp_rx` to `standalone_file_logger` to allow logging to recover in case of an overflow in the rx queue.

In this case to mimic `sbp_rx`, we stuff the `pk_endpoint` context, the reader handle and endpoint name into it's own context that's used to reattach (`detach`, `destroy`, `create` and `attach`) to the proper underlying uds socket. This has the opportunity to be folded into `libpiksi` as a pattern but for now I am simply reproducing and applying it.

### CODE REVIEW

**Comment by silverjam** [comment]
Why can't we use sbp_rx directly?

**Comment by benjaminaltieri** [comment]
@silverjam afaik `sbp_rx` uses the `sbp_process` api provided by `libsbp` which works based on a whitelist. I thought about adding a 'return all' sort of feature to `libsbp` which would deframe and simply return all message types but that sounded like more work than just porting the reconnect logic

**Comment by silverjam** [comment]
@benjaminaltieri ok, let's log a story to do a "return all" API on master

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.2.11-2-gc9c381c3
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=850280)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.11-2-gc9c381c3&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.11-2-gc9c381c3&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.2.11-2-gc9c381c3
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.2.11-2-gc9c381c3)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.2.11-2-gc9c381c3/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.2.11-2-gc9c381c3

**Comment by denniszollo** [comment]
It may be useful to have a "enabled_sbp_message" setting on standalone logger that defaults to "" (all enabled).  Not sure what other people think, but then the interface would be more flexible for different use cases.

**Comment by benjaminaltieri** [comment]
So unfortunately this does not fix the issue with standalone logging as reported [ESD-981](https://swift-nav.atlassian.net/browse/ESD-981) but I did verify  that the endpoint does reconnect, whereas in `v2.2.11` the main thread gets stuck on a `poll` call.
 
Running the following
```
strace standalone_file_logger -d /media/sda1/ -s 'ipc:///var/run/sockets/external.pub'
```
Gives the following output:
[strace_output_standalone_on_2.2.11.txt](https://github.com/swift-nav/piksi_buildroot/files/2738565/strace_output_standalone_on_2.2.11.txt)
vs. with reconnect logic:
[strace_output_standalone_sub_poller_reconnect_logic.txt](https://github.com/swift-nav/piksi_buildroot/files/2738571/strace_output_standalone_sub_poller_reconnect_logic.txt)

**Pull request merged**
