### PR TITLE
Build improvements

### PR DESCRIPTION
**Pull request by jacobmcnamee**
- Update Buildroot to 2017.02.1
- Update `BR2_EXTERNAL` tree (Buildroot now supports multiple external trees)
- Add host defconfig
- Add host build packages to Dockerfile
- Add host targets to Makefile
- Build and run tests using Buildroot
- Remove CMake for host builds
- Add Travis job for host build
- Publish `build.out` and `host_build.out`

TODO: 
- [x] Update U-Boot once https://github.com/swift-nav/u-boot-xlnx/pull/33 and https://github.com/swift-nav/u-boot-xlnx/pull/32 are merged

/cc @swift-nav/firmware @mfine @axlan

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-94-g219f06c
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-94-g219f06c/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-94-g219f06c/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-94-g219f06c

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-99-g6c4a465
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-99-g6c4a465/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-99-g6c4a465/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-99-g6c4a465

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-99-gddfe206
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-99-gddfe206/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-99-gddfe206/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-99-gddfe206

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-100-gf810aca
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-100-gf810aca/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-100-gf810aca/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-100-gf810aca

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-102-g85630a3
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-102-g85630a3/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-102-g85630a3/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-102-g85630a3

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-103-g38076ab
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-103-g38076ab/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-103-g38076ab/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-103-g38076ab

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-103-gaaabd4b
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-103-gaaabd4b/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-103-gaaabd4b/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-103-gaaabd4b

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-103-gaaabd4b
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-103-gaaabd4b/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-103-gaaabd4b/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-103-gaaabd4b

**Comment by axlan** [comment]
Awesome, glad to see the host build consolidated into build-root.

One use case I'd be interested in supporting would be host debugging. Looking at the test_standalone_file_logger, it's being run through chroot. Can I just connect GDB and debug as though it were being run directly?

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-103-g14b3640
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-103-g14b3640/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-103-g14b3640/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-103-g14b3640

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-103-g14b3640
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-103-g14b3640/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-103-g14b3640/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-103-g14b3640

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-103-g83105f0
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-103-g83105f0/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-103-g83105f0/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-103-g83105f0

**Comment by jacobmcnamee** [comment]
@axlan I think to use `gdb` inside of `chroot` we would have to add the `gdb` package (which we can easily do). Alternatively there should be no issues running without `chroot` by simply specifying `LD_LIBRARY_PATH`.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-103-g8979b89
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-103-g8979b89/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-103-g8979b89/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-103-g8979b89

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-105-gc8de330
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-105-gc8de330/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-105-gc8de330/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-105-gc8de330

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-104-g7b005fc
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-104-g7b005fc/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-104-g7b005fc/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-104-g7b005fc

**Pull request merged**
