### PR TITLE
Skylark Daemons

### PR DESCRIPTION
**Pull request by mfine**
# Skylark Upload and Download Daemons

## What

Run upload and download daemons on Piksi's linux.

## Why

Provide direct network connectivity to Skylark services. Historical connectivity
has been provided through the serial port either through the Piksi Console or
other utilities. Moving to a direct connection to Skylark services will remove a
lot of troublesome intermediaries, especially the Piksi Console, and hopefully
provide simpler and more robust network connectivity. This will completely
remove the need for external network connectivity.

## How

Setup upload and download daemons that are monitored and continuously run on
Piksi's linux - if either process crashes, they will be restarted by monit. The
upload and download daemons will be run independently for improved robustness
and simplicity.

### Settings

Upload and download daemons will continuously listen for `SKYLARK_ENABLE`
settings and will start or stop their child processes as necessary. Upload and
download daemons will also continuously listen for `SKYLARK_URL` settings and
will update the restart their child processes as necessary, but will use a
default Skylark URL in the setting's absence.

### Upload

The upload daemon will maintain a master process that continuously listens for
Skylark settings and will create child processes to receive SBP messages from
zeromq and send SBP messages to Skylark with libcurl - this should require two
child processes for zeromq and libcurl. The two child processes exchange data -
the libcurl process sends messages from the zeromq process - and will use a pipe
to exchange data between processes. The master process will restart child
processes as necessary.

### Download

The download daemon will maintain a master process that continuously listens for
Skylark settings and will create a child process to receive SBP messages from
Skylark with libcurl and send SBP messages to zeromq - this should require one
child process for libcurl. The master process will restart child processes as
necessary. Bytes will be downloaded from Skylark - how will they be
reconstituted as SBP messages?

/cc @jacobmcnamee @gsmcmullin @fnoble @ljbade 

Setup some boilerplate around these daemons and wanted to circulate this design snippet and get some feedback before digging to deeply into an implementation.

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-62-g26788e0
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-62-g26788e0/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-62-g26788e0/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-62-g26788e0

**Comment by ljbade** [comment]
Seems complicated having so many different processes. What will monitor child processes for crashes?

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-64-g43727ba
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-64-g43727ba/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-64-g43727ba/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-64-g43727ba

**Comment by mfine** [comment]
@ljbade yeah, probably a bad idea. Should probably just listen for config changes and then crash and let monit bring it up with the new configuration or something. Going to end up skipping that part for this prototype as I'm going to run out of time.

I filled in more implementation that I have compiling and will try running on the device tomorrow:
https://github.com/swift-nav/piksi_buildroot/blob/mfine/skylark-daemons/package/skylark_download_daemon/src/main.c
https://github.com/swift-nav/piksi_buildroot/blob/mfine/skylark-daemons/package/skylark_upload_daemon/src/main.c

Any gotchas anyone can point out in there would be appreciated.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-65-gfcb874b
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-65-gfcb874b/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-65-gfcb874b/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-65-gfcb874b

**Comment by ljbade** [comment]
Key thing I can think of in here, is handling HTTPS with libcurl. From memory you need to either include and load the certificate "package" aka a folder on known root certificates, or using certificate pinning. Pinning has advantage that you can safeguard against man-in-the-middle attacks, but you need to make sure you also have a backup certificate. (Maybe Amazon certificate infrastructure can handle this for you).

You will also need to compile in a SSL library. I'd recommend avoiding OpenSSL and go for one of the lighterweight SSL libraries libcurl can use. OpenSSL is a PITA to get compiling correctly on ARM, and contains heaps of obsolete crud you need to disable to avoid getting a bloated binary.

**Comment by mfine** [comment]
Once connected to a network, need to log into piksi and:

```
$ rm /etc/resolv.conf
$ echo 'nameserver 8.8.8.8' > /etc/resolv.conf
$ date -s '2017-03-09 16:14:00'
```

Then can run `skylark_download_daemon` or `skylark_upload_daemon` from the command-line.

**Comment by mfine** [comment]
I added some debugging and have poor visibility into what might be going wrong. I can connect to Skylark and activate the libcurl callbacks, but I have issues hooking into the zmq loop for the upload and I'm not sure piksi is getting the right messages on download. Hopefully a lot of the groundwork is laid here and there's some just messing around with the zmq setup and sbp framing.

/cc @mookerji @peddie @fnoble @jacobmcnamee

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-67-gf76c94c
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-67-gf76c94c/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-67-gf76c94c/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-67-gf76c94c

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-68-g078762f
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-68-g078762f/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-68-g078762f/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-68-g078762f

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-69-g794b3d8
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-69-g794b3d8/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-69-g794b3d8/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-69-g794b3d8

**Comment by mfine** [comment]
Got things up and running to where Skylark is seeing positions from the device, and the device seems to be getting observations down and ingested (can't verify that the obs are correct because don't have a console or serial port attached). Able to see logs on the server and tail the daemons on the device.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-71-gcf6d9b9
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-71-gcf6d9b9/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-71-gcf6d9b9/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-71-gcf6d9b9

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-73-ge40bc53
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-73-ge40bc53/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-73-ge40bc53/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-73-ge40bc53

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-73-ge40bc53
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-73-ge40bc53/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-73-ge40bc53/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-73-ge40bc53

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-73-ge40bc53
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-73-ge40bc53/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-73-ge40bc53/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-73-ge40bc53

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-74-g4a5a97d
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-74-g4a5a97d/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-74-g4a5a97d/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-74-g4a5a97d

**Comment by mookerji** [comment]
Closed in favor of https://github.com/swift-nav/piksi_buildroot/pull/154.

**Pull request closed without merging**
