### PR TITLE
[WIP] Piksi endpoint fix-ups + SmoothPose NAP workaround [ESD-968]

### PR DESCRIPTION
**Pull request by silverjam**

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.2.7-9-g270f7d00
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=808691)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.7-9-g270f7d00&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.7-9-g270f7d00&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.2.7-9-g270f7d00
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.2.7-9-g270f7d00)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.2.7-9-g270f7d00/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.2.7-9-g270f7d00

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.2.8-8-g6c543535
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=809727)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.8-8-g6c543535&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.8-8-g6c543535&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.2.8-8-g6c543535
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.2.8-8-g6c543535)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.2.8-8-g6c543535/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.2.8-8-g6c543535

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.2.8-10-g75f9f803
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=809857)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.8-10-g75f9f803&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.8-10-g75f9f803&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.2.8-10-g75f9f803
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.2.8-10-g75f9f803)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.2.8-10-g75f9f803/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.2.8-10-g75f9f803

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.2.8-13-gb6ab415b
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=809949)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.8-13-gb6ab415b&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.8-13-gb6ab415b&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.2.8-13-gb6ab415b
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.2.8-13-gb6ab415b)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.2.8-13-gb6ab415b/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.2.8-13-gb6ab415b

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.2.8-16-g15de98b5
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=810364)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.8-16-g15de98b5&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.8-16-g15de98b5&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.2.8-16-g15de98b5
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.2.8-16-g15de98b5)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.2.8-16-g15de98b5/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.2.8-16-g15de98b5

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.2.8-16-g15de98b5
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=810455)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.8-16-g15de98b5&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.8-16-g15de98b5&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.2.8-16-g15de98b5
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.2.8-16-g15de98b5)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.2.8-16-g15de98b5/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.2.8-16-g15de98b5

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.2.9-21-gd584ead8
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=815527)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.9-21-gd584ead8&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.9-21-gd584ead8&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.2.9-21-gd584ead8
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.2.9-21-gd584ead8)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.2.9-21-gd584ead8/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.2.9-21-gd584ead8

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.2.9-22-g56daf0e2
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=815572)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.9-22-g56daf0e2&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.9-22-g56daf0e2&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.2.9-22-g56daf0e2
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.2.9-22-g56daf0e2)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.2.9-22-g56daf0e2/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.2.9-22-g56daf0e2

**Comment by silverjam** [comment]
Add a monitor script, was able to see that it was able to detect a failure scenario and correct it:

```
Jan  1 00:00:18 piksi local0.info smoothpose_daemon[2447]: Initiating IP check...
Jan  1 00:00:18 piksi local0.info smoothpose_daemon[2447]: IP Unlock: Feature Key Index
Jan  1 00:00:18 piksi local0.debug smoothpose_daemon[2447]: Is IP locked
Jan  1 00:00:18 piksi local0.debug smoothpose_daemon[2447]: IP Unlock: Feature Key Index
Jan  1 00:00:18 piksi local0.debug smoothpose_daemon[2447]: Is IP locked
Jan  1 00:00:18 piksi local0.debug smoothpose_daemon[2447]: IP Challenge
Jan  1 00:00:18 piksi authpriv.notice sudo:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/pose_daemon_monitor
Jan  1 00:00:18 piksi daemon.info pose_daemon_monitor: Starting...
Jan  1 00:00:18 piksi local0.debug smoothpose_daemon[2447]: IP Challenge
Dec 17 20:55:52 piksi daemon.warn pose_daemon_monitor: Restarting Piksi INS (license check appears to be stuck)...
Dec 17 20:55:53 piksi local0.info smoothpose_daemon[2897]: Initiating IP check...
Dec 17 20:55:53 piksi local0.info smoothpose_daemon[2897]: IP Unlock: Feature Key Index
Dec 17 20:55:53 piksi local0.debug smoothpose_daemon[2897]: Is IP locked
Dec 17 20:55:53 piksi local0.debug smoothpose_daemon[2897]: IP Challenge
Dec 17 20:55:53 piksi local0.info smoothpose_daemon[2897]: Inertial Navigation license verification complete.
Dec 17 20:55:53 piksi local0.info smoothpose_daemon[2897]: Smoothpose mode: Loosely Coupled
Dec 17 20:55:53 piksi daemon.info pose_daemon_monitor: Stopping...
```

Particularly this line:
```
Dec 17 20:55:52 piksi daemon.warn pose_daemon_monitor: Restarting Piksi INS (license check appears to be stuck)...
```

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.2.9-23-g9c0a4f41
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=815687)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.9-23-g9c0a4f41&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.9-23-g9c0a4f41&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.2.9-23-g9c0a4f41
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.2.9-23-g9c0a4f41)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.2.9-23-g9c0a4f41/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.2.9-23-g9c0a4f41

**Comment by silverjam** [comment]
Split this PR into 4 separate PRs:
- https://github.com/swift-nav/piksi_buildroot/pull/1078
- https://github.com/swift-nav/piksi_buildroot/pull/1069
- https://github.com/swift-nav/piksi_buildroot/pull/1072
- https://github.com/swift-nav/piksi_buildroot/pull/1075

**Comment by silverjam** [comment]
This was staging area for a bunch of fixes, not needed anymore.

**Pull request closed without merging**
