### PR TITLE
Add link to HITL dashboard artifacts page

### PR DESCRIPTION
**Pull request by fnoble**

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v0.1-2-ge58ea21
+ [s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v0.1-2-ge58ea21](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v0.1-2-ge58ea21/)
+ [Artifacts](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v0.1-2-ge58ea21/)

**Comment by anonymous-travis-swiftnav** [comment]
## v0.1-2-gffb35d2
+ [Artifacts (HITL Dashboard)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v0.1-2-gffb35d2/)+ [Artifacts (S3) s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v0.1-2-gffb35d2](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v0.1-2-gffb35d2/)

**Comment by anonymous-travis-swiftnav** [comment]
## v0.1-2-g66df84a
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v0.1-2-g66df84a/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v0.1-2-g66df84a/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v0.1-2-g66df84a

**Comment by anonymous-travis-swiftnav** [comment]
## v0.1-2-gb91509e
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v0.1-2-gb91509e/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v0.1-2-gb91509e/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v0.1-2-gb91509e

**Comment by mfine** [comment]
:shipit:  Looks good!

**Pull request merged**
