### PR TITLE
Revert "Sync over existing libs and includes that buildroot has installed"

### PR DESCRIPTION
**Pull request by mfine**
Reverts swift-nav/piksi_buildroot#441

### CODE REVIEW

**Comment by mfine** [comment]
Artifacts generated:

```
$ aws s3 ls --recursive s3://swiftnav-artifacts/piksi_buildroot/v1.2.0-develop-2017122914-4         
2017-12-29 12:05:23    4564139 piksi_buildroot/v1.2.0-develop-2017122914-4-g924fa58/v3/prod/PiksiMulti-DEV-v1.2.0-develop-2017122914-4.bin
2017-12-29 12:05:24     514967 piksi_buildroot/v1.2.0-develop-2017122914-4-g924fa58/v3/prod/PiksiMulti-FAILSAFE-v1.2.0-develop-2017122914-4.bin
2017-12-29 12:05:25   16323546 piksi_buildroot/v1.2.0-develop-2017122914-4-g924fa58/v3/prod/PiksiMulti-v1.2.0-develop-2017122914-4.bin
2017-12-29 12:05:22       8467 piksi_buildroot/v1.2.0-develop-2017122914-4-g924fa58/v3/prod/boot.bin
2017-12-29 12:05:20    4837238 piksi_buildroot/v1.2.0-develop-2017122914-4-g924fa58/v3/prod/build.out
2017-12-29 11:45:08    3397856 piksi_buildroot/v1.2.0-develop-2017122914-4-g924fa58/v3/prod/host_build.out
2017-12-29 12:04:56    4837525 piksi_buildroot/v1.2.0-develop-2017122914-4-g924fa58/v3/prod/sdk_build.out
2017-12-29 12:05:27   16024783 piksi_buildroot/v1.2.0-develop-2017122914-4-g924fa58/v3/prod/uImage.piksiv3_prod
```

**Comment by silverjam** [comment]
@mfine Any idea how #441 caused this issue, I don't see anything obvious in that PR, #435 seemed to have issues with the publish script... Maybe the issue was that the previous release tag included #435?

**Comment by silverjam** [comment]
@mfine never mind, build succeeded locally, but silently failed on travis

**Pull request merged**
