### PR TITLE
Make setup of runit service dirs blocking [ESD-886]

### PR DESCRIPTION
**Pull request by silverjam**

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.1.0-develop-2018111323-5-gcd6dfac6
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=770525)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.1.0-develop-2018111323-5-gcd6dfac6&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.1.0-develop-2018111323-5-gcd6dfac6&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.1.0-develop-2018111323-5-gcd6dfac6
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.1.0-develop-2018111323-5-gcd6dfac6)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.1.0-develop-2018111323-5-gcd6dfac6/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.1.0-develop-2018111323-5-gcd6dfac6

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.1.0-develop-2018111323-5-gcd6dfac6
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=770576)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.1.0-develop-2018111323-5-gcd6dfac6&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.1.0-develop-2018111323-5-gcd6dfac6&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.1.0-develop-2018111323-5-gcd6dfac6
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.1.0-develop-2018111323-5-gcd6dfac6)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.1.0-develop-2018111323-5-gcd6dfac6/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.1.0-develop-2018111323-5-gcd6dfac6

**Comment by silverjam** [comment]
Tested on bench and seeing better output from service start-up:
```
Retrieving piksi_firmware.elf from network
PK6249570a2a6043bcb5 100% |*******************************|  2391k  0:00:00 ETA
Copying piksi_firmware.elf from network
Retrieving piksi_fpga.bit from network
PK6249570a2a6043bcb5 100% |*******************************|  3950k  0:00:00 ETA
Copying piksi_fpga.bit from network
Retrieving config.ini from network
tftp: server error: (1) File not found
Retrieving init_script.sh from network
tftp: server error: (1) File not found
Runit start response: y
ok: run: /var/service/endpoint_router_nmea: (pid 928) 0s
ok: run: /var/service/endpoint_router_rtcm3: (pid 956) 1s
ok: run: /var/service/endpoint_router_sbp: (pid 986) 0s
ok: run: /var/service/sbp_fileio_daemon_external: (pid 1091) 0s
ok: run: /var/service/sbp_fileio_daemon_firmware: (pid 1178) 0s
ok: run: /var/service/sbp_settings_daemon: (pid 1208) 0s
Starting ntrip_daemon
Starting orion_daemon
ok: run: /var/service/piksi_system_daemon: (pid 1329) 0s
ok: run: /var/service/ports_daemon: (pid 1384) 0s
Starting rpmsg_piksi
```

**Pull request merged**
