### PR TITLE
Encode MAX size when appropriate

### PR DESCRIPTION
**Pull request by anth-cole**
master version of https://github.com/swift-nav/piksi_buildroot/pull/249

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-140-gccf8170
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-140-gccf8170/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-140-gccf8170/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-140-gccf8170

**Comment by pgrgich** [comment]
Lgtm.

**Comment by pgrgich** [comment]
Doesn't the debug bool also need to be changed from an extern like in the release branch?

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-141-g64aaf8c
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-141-g64aaf8c/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-141-g64aaf8c/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-141-g64aaf8c

**Pull request merged**
