### PR TITLE
Filter settings write messages

### PR DESCRIPTION
**Pull request by silverjam**
## Overview of changes

This set of changes adds support for a "settings write whitelist".  The whitelist allows writes to settings values to be whitelisted on a per port basis.  The whitelists are stored in `/etc/filter.d/settings_whitelist` -- the default configuration is to whitelist all current settings except for the new `ssh.enable` setting, which is only writeable no the uart and usb serial interfaces.

This change also introduces support for the `ssh.enable` settings, which allows the ssh daemon to be disabled dynamically.  The start script will look for the presence of a /persist/disable_ssh file and exit if it is present.  SSH can be re-enabled once per boot by deleting this file and restarting the SSH service, or by changing the `ssh.enable` setting back to True.

To implement this a new package `cmph` was introduced (http://cmph.sourceforge.net/).  The package implements a "minimal perfect hash" for implementing the whitelist.  The settings whitelist is formatted as follows:

```
section_name_1.setting_name_1
section_name_2.setting_name_2
section_name_N.setting_name_N
```

No whitespace other than newlines are allowed in the file.  The cmph library will process this file and produce a constant time look-up table for implementing the whitelist.  Using the information from the `cmph` library we build an internal table with the index from `cmph` and the whitelist settings value from the config file.  Matches into the white consitute: (1) parsing the SBP settings write message; (2) asking the `cmph` package to hash the value; (3) checking that the value retrieved by the hash actually matches the setting that's being written; (4) accepting or rejected the write based on the result of the comparison in item (3).

The `zmq_adapter` filter mechanics were changed to allow filters to be chained.  A list of "filter specifications" is now provided to `filter_create`.  The list of filters is walked and provided a message to filter, the first filter to reject the message wins.

To verify these changes, unit testing was introduced for `zmq_adapter`, which are also run under Valgrind to prove the memory safety of the changes.  See `zmq_adapter.mk` for details on how the tests are run under Valgrind.

## Parallel changes needed in the console

We'll need changes in the console similar to the current handling of read-only settings, which will know which settings are read-only based on the current type of connection to the Piksi.  For now the `ssh.enable` would be the only setting that changes it's read-only status based on the connection type, but others could be added (such as port configurations, network config, etc).

## Notes for reviewers

- The diff for `filter_settings_whitelist.c` was not loading for me through the GitHub web UI, instead [use this link to view the whole file without the diff UI](https://github.com/swift-nav/piksi_buildroot/blob/5bee8d4c44a9c592dd09043f6c711924bd7ef73c/package/zmq_adapter/zmq_adapter/src/filter_settings_whitelist.c).
- The changes to `filter.c` are obscured by the GitHub PR diff here, the most relevant change sets are: [28ddd8](https://github.com/swift-nav/piksi_buildroot/commit/28ddd8642fa7c1b6bb5abbd9ba9438ac821c9f1d#diff-370b072e7ad1c38940eb96d5f7f43fdc), [22ecec](https://github.com/swift-nav/piksi_buildroot/commit/22ecec52c9a2892cd02bc582ad8a76f69d20f28a#diff-5f3a0505cdfc97f0c62cf2c7c26a981c), [8bcf1a](https://github.com/swift-nav/piksi_buildroot/commit/8bcf1a1997299d1702506ccd7d926e24f8e04abe#diff-5f3a0505cdfc97f0c62cf2c7c26a981c), [d6a24c](https://github.com/swift-nav/piksi_buildroot/commit/d6a24cd7d337288e8619c8fa053d90b608660a2d#diff-5f3a0505cdfc97f0c62cf2c7c26a981c), [c65802](https://github.com/swift-nav/piksi_buildroot/commit/c65802efc9322ccdd448115865a7ae97283cdcad#diff-5f3a0505cdfc97f0c62cf2c7c26a981c), [6e7ba9](https://github.com/swift-nav/piksi_buildroot/commit/6e7ba90351643a1116ee298e53e4e3153e43c2f2#diff-5f3a0505cdfc97f0c62cf2c7c26a981c), [dce4ca](https://github.com/swift-nav/piksi_buildroot/commit/dce4ca9ee687f13453fa12578d797116557364b9#diff-370b072e7ad1c38940eb96d5f7f43fdc).

## Other changes

Other miscellaneous changes:
+ Reorganized the `--filter-out` config files into `/etc/filter.d/filter_out/<interface_name>`
+ Added a `docker-exec` command for getting more than one shell inside of a `docker-run` container
+ Enabled additional compiler warnings and fixed them throughout zmq_adapter, added `cast_check.h` helper macros for verifying the sanity of the the type conversions

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.3.0-develop-2018011303-4-g98a2187
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018011303-4-g98a2187/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.3.0-develop-2018011303-4-g98a2187/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018011303-4-g98a2187

**Comment by anonymous-travis-swiftnav** [comment]
## v1.3.0-develop-2018011303-6-gb428f36
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018011303-6-gb428f36/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.3.0-develop-2018011303-6-gb428f36/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018011303-6-gb428f36

**Comment by anonymous-travis-swiftnav** [comment]
## v1.3.0-develop-2018012001-13-g4025056
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018012001-13-g4025056/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.3.0-develop-2018012001-13-g4025056/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018012001-13-g4025056

**Comment by anonymous-travis-swiftnav** [comment]
## v1.3.0-develop-2018012001-14-gdb3e93e
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018012001-14-gdb3e93e/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.3.0-develop-2018012001-14-gdb3e93e/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018012001-14-gdb3e93e

**Comment by anonymous-travis-swiftnav** [comment]
## v1.3.0-develop-2018012001-16-ge0c6839
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018012001-16-ge0c6839/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.3.0-develop-2018012001-16-ge0c6839/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018012001-16-ge0c6839

**Comment by anonymous-travis-swiftnav** [comment]
## v1.3.0-develop-2018012001-26-g1413e2d
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018012001-26-g1413e2d/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.3.0-develop-2018012001-26-g1413e2d/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018012001-26-g1413e2d

**Comment by anonymous-travis-swiftnav** [comment]
## v1.3.0-develop-2018012001-30-g7c62bd1
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018012001-30-g7c62bd1/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.3.0-develop-2018012001-30-g7c62bd1/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018012001-30-g7c62bd1

**Comment by anonymous-travis-swiftnav** [comment]
## v1.3.0-develop-2018012001-31-ge0c68ed
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018012001-31-ge0c68ed/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.3.0-develop-2018012001-31-ge0c68ed/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018012001-31-ge0c68ed

**Comment by anonymous-travis-swiftnav** [comment]
## v1.3.0-develop-2018012001-32-gfc2408f
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018012001-32-gfc2408f/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.3.0-develop-2018012001-32-gfc2408f/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018012001-32-gfc2408f

**Comment by anonymous-travis-swiftnav** [comment]
## v1.3.0-develop-2018012001-33-g73137e3
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018012001-33-g73137e3/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.3.0-develop-2018012001-33-g73137e3/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018012001-33-g73137e3

**Comment by anonymous-travis-swiftnav** [comment]
## v1.3.0-develop-2018012001-36-ga857c89
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018012001-36-ga857c89/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.3.0-develop-2018012001-36-ga857c89/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018012001-36-ga857c89

**Review by gsmcmullin — APPROVED** [review]
The implementation looks great.  Having many (almost) identical whitelists makes it less than obvious what is going on.  Blacklists would be a little simpler from this point of view.

**Review by mfine — COMMENTED** [review]
This is a very large changeset - briefly it looks ok, but other opinions would be more valuable. :+1: on Gareth's point about a settings black list being more explicit and clear here.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.3.0-develop-2018013000-29-g07c947e
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018013000-29-g07c947e/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.3.0-develop-2018013000-29-g07c947e/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018013000-29-g07c947e

**Comment by silverjam** [comment]
A blacklist is not secure by default in this context, I wanted to avoid a situation where something like `ssh.enable` would get renamed or things gets omitted/misconfigured and thus would allow a write of a "sensitive" setting.

I think something along these lines is going to be needed for future security work, I agree we could work on dressing up the whitelist so that there isn't so much duplicated information, but this was the simplest solution from a parsing standpoint.

I'm thinking that the future settings whitelist would allow more fine grained control of what settings get exposed.  That is, some settings should only be visible on "secure" or local connections (such as the SmoothPose license, and the future SSH key).

At alternative to this would be to allow zmq_adpater to be unidirectional for TCP ports, and just close off all incoming data... but I'm not sure that allows sufficient flexibility.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.3.0-develop-2018013000-32-g9ad3091
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018013000-32-g9ad3091/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.3.0-develop-2018013000-32-g9ad3091/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018013000-32-g9ad3091

**Comment by anonymous-travis-swiftnav** [comment]
## v1.3.0-develop-2018020221-31-g8126dab
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018020221-31-g8126dab/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.3.0-develop-2018020221-31-g8126dab/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018020221-31-g8126dab

**Pull request closed without merging**
