### PR TITLE
Convert sbp_zmq and sbp_settings to libraries

### PR DESCRIPTION
**Pull request by jacobmcnamee**
- Add `sbp_zmq` and `sbp_settings` libraries
- Integrate with `piksi_system_daemon`

Fixes issue where `piksi_system_daemon` did not properly wait for settings registration replies.

/cc @swift-nav/firmware

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v0.2-16-gd5143f5
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v0.2-16-gd5143f5/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v0.2-16-gd5143f5/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v0.2-16-gd5143f5

**Comment by anonymous-travis-swiftnav** [comment]
## v0.2-16-g9e0fd71
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v0.2-16-g9e0fd71/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v0.2-16-g9e0fd71/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v0.2-16-g9e0fd71

**Comment by anonymous-travis-swiftnav** [comment]
## v0.3.0-4-gf9b532f
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v0.3.0-4-gf9b532f/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v0.3.0-4-gf9b532f/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v0.3.0-4-gf9b532f

**Comment by anonymous-travis-swiftnav** [comment]
## v0.3.0-4-g2f74233
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v0.3.0-4-g2f74233/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v0.3.0-4-g2f74233/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v0.3.0-4-g2f74233

**Comment by anonymous-travis-swiftnav** [comment]
## v0.3.0-29-ge79041e
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v0.3.0-29-ge79041e/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v0.3.0-29-ge79041e/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v0.3.0-29-ge79041e

**Comment by jacobmcnamee** [comment]
Bench tested to confirm that `piksi_system_daemon` still works as expected.

**Pull request merged**
