### PR TITLE
added makefile option to rebuild individual package

### PR DESCRIPTION
**Pull request by axlan**

### CODE REVIEW

**Comment by mfine** [comment]
sweet!

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-182-g8bd4545
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-182-g8bd4545/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-182-g8bd4545/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-182-g8bd4545

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-182-gc4514ad
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-182-gc4514ad/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-182-gc4514ad/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-182-gc4514ad

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-182-g128431f
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-182-g128431f/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-182-g128431f/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-182-g128431f

**Pull request merged**
