### PR TITLE
hide can settings if can_ports flag not enabled [ESD-883]

### PR DESCRIPTION
**Pull request by yizow**
The CAN port settings should be visible if and only if the can_ports flag is on. That flag is set if 
```
[experimental_flags]
can_ports = True
```
Is in `config.ini`

### CODE REVIEW

**Comment by silverjam** [comment]
Not a huge fan of passing around a flag just for CAN things, would prefer if we could have CAN support someone "self-assemble" by registering itself to a list somehow, but I suppose this will work for now (presumably we'll be able tor remove this once CAN is fully supported/implemented?).

**Comment by silverjam** [comment]
Needs some clang-format love according to Jenkins:
```
+ git --no-pager diff --name-only HEAD

+ [ -s /tmp/clang-format-diff ]

+ echo clang-format warning found

clang-format warning found

+ git --no-pager diff

diff --git a/package/ports_daemon/ports_daemon/src/whitelists.c b/package/ports_daemon/ports_daemon/src/whitelists.c

index 4dfab5e74..77d8c52f8 100644

--- a/package/ports_daemon/ports_daemon/src/whitelists.c

+++ b/package/ports_daemon/ports_daemon/src/whitelists.c

@@ -534,8 +534,7 @@ int whitelist_notify(void *context)

 int whitelists_init(pk_settings_ctx_t *settings_ctx, bool can_enabled)

 {

   for (int i = 0; i < PORT_MAX; i++) {

-    if ((strncmp(port_whitelist_config[i].name, "can", 3) == 0) &&

-         !can_enabled) {

+    if ((strncmp(port_whitelist_config[i].name, "can", 3) == 0) && !can_enabled) {

       continue;

     }

 

+ exit 1

script returned exit code 1
```

**Comment by silverjam** [comment]
@yizow Ideally changes for 2.2 should be made on the 2.2 branch so you don't need to manually backport the change.  The PR automation only goes from release -> master.

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.1.0-develop-2018121420-5-g8daa439f

These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.

### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=817531)

### gnss-analysis results
At least one run must complete for these links to have data.

#### passfail"
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&summary_type=q50&groupby_key=firmware&firmware_versions=v2.1.0-develop-2018121420-5-g8daa439f&build_type=buildroot_pr&display_type=table)

#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/metrics_preset=detailed&scenario=live-roof-650-townsend-post&summary_type=q50&groupby_key=firmware&firmware_versions=v2.1.0-develop-2018121420-5-g8daa439f&build_type=buildroot_pr&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.1.0-develop-2018121420-5-g8daa439f
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.1.0-develop-2018121420-5-g8daa439f)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.1.0-develop-2018121420-5-g8daa439f/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.1.0-develop-2018121420-5-g8daa439f

**Pull request merged**
