### PR TITLE
Integrate piksi_ins_ref repo with buildroot

### PR DESCRIPTION
**Pull request by silverjam**
TODO:
  - [x] Fail silently if the user does not have access to the private repository (probably do this with an environment variable that the buildroot script can check).

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017111721-15-g767eb99
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017111721-15-g767eb99/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017111721-15-g767eb99/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017111721-15-g767eb99

**Comment by jck** [comment]
Currently fails on linux:
`Bad owner or permissions on /root/.ssh/config`

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017112220-9-gfcb9884
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017112220-9-gfcb9884/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017112220-9-gfcb9884/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017112220-9-gfcb9884

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017112220-10-g91ee721
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017112220-10-g91ee721/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017112220-10-g91ee721/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017112220-10-g91ee721

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017112220-11-g648a5e8
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017112220-11-g648a5e8/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017112220-11-g648a5e8/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017112220-11-g648a5e8

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017112220-20-g7bba8b9
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017112220-20-g7bba8b9/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017112220-20-g7bba8b9/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017112220-20-g7bba8b9

**Comment by silverjam** [comment]
@jck please review again when you get a chance

**Pull request merged**
