### PR TITLE
CMake and unit test machinery for developer host testing.

### PR DESCRIPTION
**Pull request by mookerji**
/cc @axlan @jacobmcnamee

### CODE REVIEW

**Comment by mookerji** [comment]
Replaces https://github.com/swift-nav/piksi_buildroot/pull/161 so that Travis works (requires build parameters off of swift-nav).

**Comment by jacobmcnamee** [comment]
I don't have time this week to go through everything, but
- `package` directory is for buildroot packages
- I'm not a fan of adding all the dependencies as submodules. They are already versioned as buildroot packages, and the buildroot paradigm is to download during the build process. Can we not reuse the existing configs and/or downloaded packages?

**Comment by axlan** [comment]
CMake supports downloading the packages and not needing the source comitted in the repo, but I had other feedback this was preferred since it let the versioning be handled just by git. 

There isn't a straightforward way to share the versioning between the local build and buildroot. My understanding is we could point to buildroot/package/<pkgname>/<pkgname>.mk and grab the <pkgname>_VERSION variable and feed this into the cmake external package manager. This might be worth pursuing if we think it's important to share the versioning of the libraries between the host and buildroot.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-70-g4ec6fe7
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-70-g4ec6fe7/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-70-g4ec6fe7/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-70-g4ec6fe7

**Comment by mookerji** [comment]
@jacobmcnamee, yeah, I'm not the biggest fan of the fact that we started with submodules and are managing these that way. I don't think that @axlan and I realized that it would be that easy to use buildroot's package management here, in which case the only submodule would be googletest.

**Comment by axlan** [comment]
Just to clarify I think it's still valuable to have the actual management of downloading the libraries separate between the host builds (with cmake) and buildroot. It might create duplicates of the library repos, but it makes it so that the state of the builds are totally independent.

**Comment by mookerji** [comment]
@jacobmcnamee, @axlan and I talked about it and I believe he's going to give a go at seeing if we can manage the host-side build with packages managed by buildroot. I'm going to move the file locations so as to separate the host packages from build root.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-71-g3dfe768
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-71-g3dfe768/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-71-g3dfe768/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-71-g3dfe768

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-71-gae0c035
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-71-gae0c035/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-71-gae0c035/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-71-gae0c035

**Comment by axlan** [comment]
after digging in a bit it turns out that while you can pretty simply use buildroot to download the source for you:
`make config
BR2_EXTERNAL=/media/data/src/piksi_buildroot HW_CONFIG=prod make -C buildroot zeromq-extract czmq-extract libsbp-extract`
The version of ZMQ packaged with buildroot does not build with cmake. in addition there are a few other frictions with mixing the toolchains. 

Based on this we're going ahead with the other strategy I mentioned where we get rid of the submodules and have cmake directly pull down the versions closest to those specified for buildroot. This adds some extra upkeep to keep the libraries in sink, but this seems to be the best compromises in pain points.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-75-gb68f79a
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-75-gb68f79a/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-75-gb68f79a/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-75-gb68f79a

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-75-gf02c6f9
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-75-gf02c6f9/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-75-gf02c6f9/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-75-gf02c6f9

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-78-gf30d90c
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-78-gf30d90c/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-78-gf30d90c/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-78-gf30d90c

**Pull request merged**
