### PR TITLE
Build variant support [ESD-1085]

### PR DESCRIPTION
**Pull request by silverjam**
## Design Notes
Adds 2 new config files for controlling build variants and external artifacts:
+ `build-variants.yaml`: specifies the configuration of a build variant, how to build the config, what external artifacts are present in the variant, and what "pre-flight" checks are needed to ensure that the build succeeds
+ `external-artifacts.yaml`: A manifest specifying external artifact "sets", a particular variant will pull in a particular artifact set

Pairs with: https://github.com/swift-nav/piksi-releases/pull/94 to implement the "release process" side of this change.

## Testing
+ Spot checked that each build variant produces the artifacts that it should, and that each variant builds appropriate packages.
+ Built release image of master without variant support and built release image of this PR and compare the filesystem contents (by filename) and confirmed that they produce the some set of filenames.
+ Confirmed that the "failsafe" upgrade image is built and included in the release image
+ Tested a manual SDK build and confirmed that: (1) it cannot upgrade a release build (no encryption keys); (2) it has SSH and no INS software.

## Output paths
Output paths for variant change with this PR.  The "internal" build variant, for example will now go to `buildroot/output/internal` instead of just `buildroot/output`.

### Build Variants and External Artifacts

Build variants are controlled by the `build-variants.yaml` config file which
specifies the inputs into a variant based on a number of inputs:

+ The name of the build variant and the package that should be generated
  - `variant_name`: Controls the name of variant, a variant is selected by
    settings the `VARIANT` environment variable (if unset, `internal` is the
    default).  For example, to build the `release` variant:
    ```
    make VARIANT=release image
    ```
  - `image_name`: controls the name of output package,
    for example `'PiksiMulti-INTERNAL-{version}.bin'`
  - `encrypted`: controls wether the output package should be encrypted
+ A number pre-flight checks to verify build inputs
  - `pre_flight`: a list of scripts to run to verify the build environment
     prior to running.  For example:
    ```yaml
     pre_flight:
       - run: './scripts/verify-aws-access'
       - run: './scripts/verify-generated-configs'
    ```
    Will run the scripts `./scripts/verify-aws-access` and
    `./scripts/verify-generated-configs` -- if any of the scripts fail, then
    the build will be terminated.
+ Input config fragments
  - `config_fragments`: A list of config fragments used to generate an output
    config, for example:
    ```yaml
     config_fragments:
       - path: configs/fragments/piksiv3/core
       - blob: 'BR2_PACKAGE_PIKSI_INS_REF=y'
    ```
  - `config_output`: specifies the output path of the resulting config, for
    example `'configs/piksiv3_internal_defconfig'`
+ An output directory: specified by the `output` config field, the build
  materials from buildroot will be placed here.
+ An external artifact set: specifies a set of external artifacts that are
  inputs into the build.  The `external-artifacts.yaml` config file specifies
  these artifacts.

Example config block:

```yaml
  -
   variant:
     variant_name: 'internal'
     encrypted: false
     artifact_set: 'internal'
     image_name:
       'PiksiMulti-INTERNAL-{version}.bin'
     output: 'output/internal'
     pre_flight:
       - run: './scripts/verify-aws-access'
       - run: './scripts/verify-piksi-ins-axx'
       - run: './scripts/verify-generated-configs'
     config_fragments:
       - path: configs/fragments/piksiv3/core
       - path: configs/fragments/piksiv3/core_packages
       - path: configs/fragments/piksiv3/piksi_ins
       - blob: 'BR2_PACKAGE_PIKSI_INS_REF=y'
       - blob: 'BR2_PACKAGE_SAMPLE_DAEMON=y'
       - blob: 'BR2_PACKAGE_STARLING_DAEMON=y'
       - blob: 'BR2_PACKAGE_PIKSI_DEV_TOOLS=y'
     config_output:
       'configs/piksiv3_internal_defconfig'
```

##### Why not use kconfig options?

Using kconfig options is an alternative to implement our build variants --
(probably more obvious to those familiar with kconfig)-- this simple method of
composing fragments is more straightfoward to those not familiar with kconfig
and makes it painfully obbvious what's in each variant, available from one
top-level config file (at the expense of making it somewhat more tedious to
update configs).

##### How do I add a new package?

If you're adding a new package to the `package` dir.  Simply add the
`BR2_PACKAGE_MY_NEW_PACKAGE=y` to one of the config fragments in
`config/fragments`.  Typically this'll will be to
`configs/fragments/core_packages` so that the package is enabled for all
variants.  Currently the `nano` and `host` configs do not use fragments (or
rather they only use one fragment, and do not use the common
`configs/fragments/core_packages`), so the package will need to be manually
enabled for those variants in `configs/fragments/nano` and/or
`config/fragments/host`.  

##### How do I use kconfig to update the config?

Run menuconfig per usual:

```
make docker-shell # if running docker
make VARIANT=<variant-name> config
make -C buildroot menuconfig
# ... update config with menuconfig ...
make -C savedefconfig
```

Then use `git diff` to inspect the changes and move the necessary changes from
`configs/<variant>_defconfig` to one of the fragments in `configs/fragments`.
Use `make gen-variant-configs` (described in the next section) to update the
generated `*_defconfig` file.

##### Generating configs

An output config (specified in `config_output` field) can be generated by
running the following make commands:

```
make gen-variant-configs
```

In the general case, updates to configs should be placed in one of the
`configs/fragments` directory and a new output config must be generated for
these config changes to be utilized.  If working with `make menuconfig`
(kconfig) to update a buildroot config, see the previous section.  

#### External artifacts

The `external-artifacts.yaml` file controls what artifacts are pulled from S3 as
inputs into the build process.  These could be any number of things, but this is
primarily used to download the RTOS ELF image, FPGA bitstream, and any
pre-compiled ARM Linux binaries.

Explanation of config fields:
- `name`: a friendly name for the artifact set, used by `build-variants.yaml` to
  refer to particular artifact set.  Also used by the `gen-requirements-yaml`
  script to generate the `requirements.yaml` file that HITL consumes.
- `artifacts`: a list of artifacts that are part of the set

Explanation of fields for the entries in an `artifacts` list:
- `name`: a frieldly name of the artifact, used by the `get-named-artifact`
  script to locate a specific artifact
- `version`: the version of the specified artifact
- `s3_bucket`: the S3 bucket in which the artifact is located
- `s3_repository`: the name of the repository this artifact is sourced from, for example: `"piksi_firmware_private"`,
                   `"piksi_upgrade_tool"`, `"starling_daemon"`, etc.
- `s3_object`: the path to the actual object (file) within the repository
- `local_path`: where the file should be placed on the system
- `sha256`: a SHA256 hash of the file

All fields of the entries in the `artifacts` list are string template enabled.
Allowing for values such as `'{name}/{version}/piksiv3'`, where `{name}` refers
to the `name` field in the artifact list entry.

Example `artifact_set` config blob:

```yaml
- artifact_set:
    name: base
    artifacts:
    - name: rtos_elf
      version: v2.2.0-develop-2019040519
      s3_bucket: swiftnav-artifacts
      s3_repository: piksi_firmware_private
      s3_object: v3/piksi_firmware_v3_base.stripped.elf
      local_path: firmware/prod/piksi_firmware.elf
      sha256: 1694f19046ceafc7e4d35614c89e65c33a253adc84c910be120273c7a15e0034
    - name: fpga_bitstream
      version: v2.2.0-develop-2019040519
      s3_bucket: swiftnav-artifacts
      s3_repository: piksi_fpga
      s3_object: piksi_base_fpga.bit
      local_path: firmware/prod/piksi_fpga.bit
      sha256: 4b3450c649a94d4311e081a071a5877f316a1f4c1de7e3640b87cfac6545ce45

# ... elided for brevity ...
```

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.2.0-develop-2019041919-40-g24681cc7

These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.

### job status
+ [live-roof-650-townsend runs](https://gnss-analysis.swiftnav.com/jobs/id=1014474)
+ [live-roof-650-townsend-dropouts-zero-baseline runs](https://gnss-analysis.swiftnav.com/jobs/id=1014475)

### gnss-analysis results
At least one run must complete for these links to have data.

#### passfail
+ [live-roof-650-townsend](https://gnss-analysis.swiftnav.com/metrics_preset=pass_fail&scenario=live-roof-650-townsend&summary_type=q50&groupby_key=firmware&firmware_versions=v2.2.0-develop-2019041919-40-g24681cc7&build_type=buildroot_pr&display_type=table)
+ [live-roof-650-townsend-dropouts-zero-baseline](https://gnss-analysis.swiftnav.com/metrics_preset=pass_fail&scenario=live-roof-650-townsend-dropouts-zero-baseline&summary_type=q50&groupby_key=firmware&firmware_versions=v2.2.0-develop-2019041919-40-g24681cc7&build_type=buildroot_pr&display_type=table)

#### detailed
+ [live-roof-650-townsend](https://gnss-analysis.swiftnav.com/metrics_preset=detailed&scenario=live-roof-650-townsend&summary_type=q50&groupby_key=firmware&firmware_versions=v2.2.0-develop-2019041919-40-g24681cc7&build_type=buildroot_pr&display_type=table)
+ [live-roof-650-townsend-dropouts-zero-baseline](https://gnss-analysis.swiftnav.com/metrics_preset=detailed&scenario=live-roof-650-townsend-dropouts-zero-baseline&summary_type=q50&groupby_key=firmware&firmware_versions=v2.2.0-develop-2019041919-40-g24681cc7&build_type=buildroot_pr&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.2.0-develop-2019041919-40-g24681cc7
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.2.0-develop-2019041919-40-g24681cc7)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.2.0-develop-2019041919-40-g24681cc7/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.2.0-develop-2019041919-40-g24681cc7

**Comment by silverjam** [comment]
Just pushed update to revive NTFS util in the buildroot config.  Current release build file diff between this PR and master (w/o variant support):

```diff
--- piksi_buildroot/file_list.txt	2019-05-09 19:18:43.000000000 -0700
+++ piksi_buildroot2/file_list.txt	2019-05-10 10:33:31.000000000 -0700
@@ -26,9 +26,7 @@
 ./usr/sbin/getpcaps
 ./usr/sbin/rdate
 ./usr/sbin/pppd
-./usr/sbin/ntfsclone
 ./usr/sbin/pppoe-discovery
-./usr/sbin/ntfsresize
 ./usr/sbin/ldattach
 ./usr/sbin/killall5
 ./usr/sbin/flashcp
@@ -56,10 +54,8 @@
 ./usr/sbin/sload.f2fs
 ./usr/sbin/mtdinfo
 ./usr/sbin/flash_lock
-./usr/sbin/ntfsundelete
 ./usr/sbin/deluser
 ./usr/sbin/ubirmvol
-./usr/sbin/ntfscp
 ./usr/sbin/nbd-client
 ./usr/sbin/ifplugd
 ./usr/sbin/tftpd
@@ -74,14 +70,12 @@
 ./usr/sbin/remove-shell
 ./usr/sbin/dhcprelay
 ./usr/sbin/fsfreeze
-./usr/sbin/ntfslabel
 ./usr/sbin/nanddump
 ./usr/sbin/svlogd
 ./usr/sbin/ubidetach
 ./usr/sbin/dump.f2fs
 ./usr/sbin/fibmap.f2fs
 ./usr/sbin/mkfs.jffs2
-./usr/sbin/mkntfs
 ./usr/sbin/arping
 ./usr/sbin/pppstats
 ./usr/sbin/readprofile
@@ -279,7 +273,6 @@
 ./usr/lib/libcmph.so.0
 ./usr/lib/libevent_openssl-2.1.so.6
 ./usr/lib/libevent_core-2.1.so.6
-./usr/lib/libntfs-3g.so.88.0.0
 ./usr/lib/libpanel.so.6.0
 ./usr/lib/libsocketcan.so.2.2.1
 ./usr/lib/libfdisk.so
@@ -310,7 +303,6 @@
 ./usr/lib/pppd/2.4.7/passprompt.so
 ./usr/lib/libevent_pthreads-2.1.so.6
 ./usr/lib/libsocketcan.so
-./usr/lib/libntfs-3g.so
 ./usr/lib/libcrypto.so
 ./usr/lib/libncurses.so.6.0
 ./usr/lib/libmenu.so
@@ -344,7 +336,6 @@
 ./usr/lib/libsbp.so
 ./usr/lib/libnfnetlink.so.0.2.0
 ./usr/lib/libstdc++.so.6.0.22
-./usr/lib/libntfs-3g.so.88
 ./usr/lib/libcrypto.so.1.0.0
 ./usr/lib/libz.so.1
 ./usr/lib/libgnss_converters.so
@@ -367,7 +358,6 @@
 ./usr/lib/libevent_extra-2.1.so.6.0.2
 ./usr/lib/libcares.so
 ./usr/lib/libjson-c.so.3
-./usr/lib/ntfs-3g
 ./usr/lib/libkmod.so.2.3.2
 ./usr/lib/libstdc++.so.6.0.22-gdb.py
 ./usr/lib/libblkid.so
@@ -661,7 +651,6 @@
 ./usr/bin/sha3sum
 ./usr/bin/patch
 ./usr/bin/filan
-./usr/bin/lowntfs-3g
 ./usr/bin/nl
 ./usr/bin/nmea_daemon
 ./usr/bin/pwdx
@@ -677,7 +666,6 @@
 ./usr/bin/stream_logs_helper
 ./usr/bin/env
 ./usr/bin/standalone_file_logger
-./usr/bin/ntfs-3g.probe
 ./usr/bin/w
 ./usr/bin/bcmserver
 ./usr/bin/lslocks
@@ -722,14 +710,12 @@
 ./usr/bin/logger
 ./usr/bin/sha256sum
 ./usr/bin/blkdiscard
-./usr/bin/ntfsinfo
 ./usr/bin/users
 ./usr/bin/whoami
 ./usr/bin/crontab
 ./usr/bin/md5sum
 ./usr/bin/bunzip2
 ./usr/bin/rsync
-./usr/bin/ntfsls
 ./usr/bin/isotpsniffer
 ./usr/bin/resource_monitor
 ./usr/bin/which
@@ -791,7 +777,6 @@
 ./usr/bin/whereis
 ./usr/bin/network_daemon
 ./usr/bin/inotifywatch
-./usr/bin/ntfscat
 ./usr/bin/hostid
 ./usr/bin/ipcrm
 ./usr/bin/sz
@@ -816,7 +801,6 @@
 ./usr/bin/truncate
 ./usr/bin/sbp_fileio_flush
 ./usr/bin/unlzma
-./usr/bin/ntfscluster
 ./usr/bin/diff
 ./usr/bin/linux32
 ./usr/bin/slcand
@@ -833,13 +817,11 @@
 ./usr/bin/cansniffer
 ./usr/bin/poff
 ./usr/bin/uudecode
-./usr/bin/ntfscmp
 ./usr/bin/dump_syslog
 ./usr/bin/sbp_settings_daemon
 ./usr/bin/canlogserver
 ./usr/bin/stream_logs
 ./usr/bin/sbp_cmd_resp
-./usr/bin/ntfsfix
 ./usr/bin/resize
 ./usr/bin/softlimit
 ./usr/bin/shred
@@ -859,7 +841,6 @@
 ./usr/bin/[[
 ./usr/bin/pon
 ./usr/bin/cangen
-./usr/bin/ntfs-3g
 ./usr/bin/killall
 ./usr/bin/xzcat
 ./usr/bin/xxd
@@ -982,7 +963,6 @@
 ./sbin/mkfs.ext2
 ./sbin/mke2fs
 ./sbin/insmod
-./sbin/mount.lowntfs-3g
 ./sbin/lsmod
 ./sbin/blockdev
 ./sbin/routef
@@ -997,7 +977,6 @@
 ./sbin/pivot_root
 ./sbin/sysctl
 ./sbin/poweroff
-./sbin/mkfs.ntfs
 ./sbin/ctstat
 ./sbin/reboot
 ./sbin/blkid
@@ -1005,7 +984,6 @@
 ./sbin/depmod
 ./sbin/mkfs.vfat
 ./sbin/iplink
-./sbin/mount.ntfs-3g
 ./sbin/zcip
 ./sbin/routel
 ./sbin/slattach
```

**Comment by silverjam** [comment]
Updated testing section of this PR.  Confirmed that the "failsafe" image is produced and populated in the release image:

```shell
jason@piksi-buildroot-f9edfdbe0221:/piksi_buildroot/buildroot/output/release/target/lib$ \
> find . -name '*FAILSAFE*.bin'
./firmware/PiksiMulti-FAILSAFE.bin
```

**Comment by silverjam** [comment]
Diff between filenames produced by PBR master (without variant support) and this PR are now identical:

```
~/dev
❯ diff -u piksi_buildroot/file_list.txt  piksi_buildroot3/file_list.txt
# ... no output ...
```

**Comment by silverjam** [comment]
Release and unprotected build passed, HITL kick-off is working, merging...

**Pull request merged**
