### PR TITLE
Revert everything to v2.2.4 (for HITL retesting)

### PR DESCRIPTION
**Pull request by cbeighley**

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.2.6-4-gbf32c082
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=807330)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.6-4-gbf32c082&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.6-4-gbf32c082&groupby_key=firmware&display_type=table)

**Comment by ekalosak** [comment]
This was reverted to 2.2.4, but the pr shows 2.2.6 - just a clerical error or indicative of actual code version state?

**Comment by cbeighley** [comment]
@ekalosak It's a commit on top of the HEAD of v2.2.0-release branch, so the commit describe string reflects that. It's the same code and dependencies as v2.2.4 though.

**Comment by silverjam** [comment]
Not necessary anymore

**Pull request closed without merging**
