### PR TITLE
Update QSPI partitions for 64MB capacity, 256kB max erase size

### PR DESCRIPTION
**Pull request by jacobmcnamee**
TODO:
- [x] Test
- [x] Update U-Boot https://github.com/swift-nav/u-boot-xlnx/pull/27

/cc @swift-nav/firmware

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-42-gb6dff60
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-42-gb6dff60/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-42-gb6dff60/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-42-gb6dff60

**Comment by jacobmcnamee** [comment]
Bench tested with MT25QL01G and S25FL512S to verify `image_table_tool` and `upgrade_tool` still function as expected.

**Comment by gsmcmullin** [comment]
lgtm

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-45-g365497e
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-45-g365497e/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-45-g365497e/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-45-g365497e

**Pull request merged**
