### PR TITLE
Remove 'Piksi Buildroot' from image headers

### PR DESCRIPTION
**Pull request by jacobmcnamee**
Image header name field is limited to 32B.

/cc @swift-nav/firmware

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v0.1-26-g70b8866
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v0.1-26-g70b8866/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v0.1-26-g70b8866/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v0.1-26-g70b8866

**Comment by fnoble** [comment]
lgtm, if you have tested it

**Comment by anonymous-travis-swiftnav** [comment]
## v0.2-2-gc787b6d
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v0.2-2-gc787b6d/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v0.2-2-gc787b6d/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v0.2-2-gc787b6d

**Comment by anonymous-travis-swiftnav** [comment]
## v0.2-5-gcf3aaa1
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v0.2-5-gcf3aaa1/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v0.2-5-gcf3aaa1/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v0.2-5-gcf3aaa1

**Pull request merged**
