### PR TITLE
Disable gigabit ethernet

### PR DESCRIPTION
**Pull request by lbara**
Changed reference to bootloader so we can disable gigabit ethernet

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.1-4-ga67357c
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.1-4-ga67357c/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.1-4-ga67357c/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.1-4-ga67357c

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.1-5-gdd7de32
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.1-5-gdd7de32/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.1-5-gdd7de32/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.1-5-gdd7de32

**Comment by denniszollo** [comment]
I suggest that we test static IP TCP/IP connection against v1.1.29 with this matrix of config:

- with a computer hardwired in following config:
 - limited to 10 base T
 - limited to 100
 - auto-negotiating 
- with a computer with a gigabet capable unmanaged switch between piksi and computer with computer in the following config:
 - limited to 10 base T
 - limited to 100 
 - auto-negotiating 

- with a computer with an old style cable (only two twisted pair) through a switch

- DHCP in office

**Comment by jkretzmer** [comment]
This change results in the TXCLK and RXCLK both being set to 25 MHz. The CLK125 pin is disabled.

I performed the following validation of the production image: once using the Piksi Multi Host Board and using the Duro hardware.

- Flashed production image on to device (via scp + upgrade_tool)
- Disconnected power / ethernet
- Reconnected power
- Probed TXCLK - result: 25 MHz
- Probed RXCLK - result: 25 MHz
- Probed CLK125 - result: no signal
- Connected ethernet cable
- Probed TXCLK - result: 25 MHz
- Probed RXCLK - result: 25 MHz
- Probed CLK125 - result: no signal
- Connected to device using Swift Console + ethernet, device behaved as exepected.
- Connected to device using SSH, device behaved as expected.
- Disconnected ethernet cable
- Probed TXCLK - result: 25 MHz
- Probed RXCLK - result: 25 MHz
- Probed CLK125 - result: no signal

These same steps should be validated with the dev bootloader. To complete testing, we should run through each of the ethernet related device functions and ensure all are working properly.

(likely incomplete) List of functionality to be tested:
- Static IP assignment
- DHCP IP assignment
- TCP Server 0
- TCP Server 1
- SSH

**Comment by jkretzmer** [comment]
This has been tested and verified to be working on a 10 Mbps link as well. I used a USB ethernet adapter and a Macbook Pro, setup manually to 10 Mbps. Connections worked as expected and the clocks behaved correctly. From the Duro side - ethtool reported a 10mbps link. I was able to change the IP of the Duro as well as receive SBP traffic over TCP on both server 0 and server 1. I enabled the IMU in order to send heavy amounts of traffic over the link. SSH also worked correctly. I feel confident that this bootloader is working correctly.

**Pull request merged**
