### PR TITLE
Generate failsafe image set

### PR DESCRIPTION
**Pull request by jacobmcnamee**
Generate failsafe image set containing only U-Boot

TODO:
- [x] Rebase once #65 is merged
- [x] Update U-Boot https://github.com/swift-nav/u-boot-xlnx/pull/21
- [x] Test

/cc @swift-nav/firmware

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v0.1-23-g302a030
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v0.1-23-g302a030/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v0.1-23-g302a030/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v0.1-23-g302a030

**Comment by anonymous-travis-swiftnav** [comment]
## v0.1-23-g851f060
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v0.1-23-g851f060/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v0.1-23-g851f060/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v0.1-23-g851f060

**Comment by fnoble** [comment]
lgtm

**Comment by anonymous-travis-swiftnav** [comment]
## v0.1-24-g6e2e00a
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v0.1-24-g6e2e00a/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v0.1-24-g6e2e00a/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v0.1-24-g6e2e00a

**Pull request merged**
