### PR TITLE
Bring in WDT fix from u-boot

### PR DESCRIPTION
**Pull request by fnoble**
Bring in fix for WDT reboot in DEV configuration from:
https://github.com/swift-nav/u-boot-xlnx/pull/22

cc: @jacobmcnamee

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v0.2-2-g00413e3
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v0.2-2-g00413e3/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v0.2-2-g00413e3/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v0.2-2-g00413e3

**Comment by denniszollo** [comment]
any reason not to merge this?

**Comment by jacobmcnamee** [comment]
It points to a branch for an open PR. I would prefer to make a few changes and then merge the U-Boot PR first.

**Comment by jacobmcnamee** [comment]
Obsoleted by https://github.com/swift-nav/u-boot-xlnx/pull/23 + https://github.com/swift-nav/piksi_buildroot/pull/75

**Pull request closed without merging**
