### PR TITLE
RTCM3 support

### PR DESCRIPTION
**Pull request by jacobmcnamee**
RTCM3 input support.
- Add RTCM3 framer to ZMQ adapter
- Add RTCM3 router
- Add `sbp_rtcm3_bridge` package (currently only prints message IDs)
- Add `RTCM3 IN` port mode setting

TODO:
- [x] Rebase once #140 is merged
- [x] Test

/cc @swift-nav/firmware @anth-cole @denniszollo

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-62-gaafc59c
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-62-gaafc59c/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-62-gaafc59c/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-62-gaafc59c

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-62-g0845a7c
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-62-g0845a7c/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-62-g0845a7c/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-62-g0845a7c

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-62-gf53c6a0
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-62-gf53c6a0/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-62-gf53c6a0/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-62-gf53c6a0

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-63-g5e348fe
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-63-g5e348fe/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-63-g5e348fe/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-63-g5e348fe

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-64-g7007aba
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-64-g7007aba/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-64-g7007aba/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-64-g7007aba

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-69-ge8d096c
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-69-ge8d096c/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-69-ge8d096c/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-69-ge8d096c

**Comment by jacobmcnamee** [comment]
Bench tested to verify that messages are making it to `rtcm3_decode_frame()`.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-69-g749b159
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-69-g749b159/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-69-g749b159/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-69-g749b159

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-68-g1e92cd0
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-68-g1e92cd0/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-68-g1e92cd0/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-68-g1e92cd0

**Comment by jacobmcnamee** [comment]
@anth-cole your task will be to implement `rtcm3_decode_frame()` in `rtcm3_decode.c`. This function takes in full RTCM3 frames (i.e. including the header and CRC). It should decode RTCM3 messages and send converted SBP messages using `sbp_message_send()` from `sbp.h`.

No idea if it works, but https://github.com/swift-nav/libswiftnav-private/blob/master/src/rtcm3.c may be useful.

**Comment by anth-cole** [comment]
@jacobmcnamee this isn't what we agreed to initially, the crc checks and decoding should be part of the low level decoder you're doing, we're doing the high level decoder to map the decoded buffers to RTCM3 message structs and then sending them on via sbp.

**Comment by jacobmcnamee** [comment]
The buffer passed to `rtcm3_decode_frame()` is a full verified RTCM frame. There is no need to look at the header or CRC bytes if they are not required. You can add a wrapper function to remove them if that is useful:

```
void rtcm3_decode_frame(const uint8_t *frame, uint32_t frame_length)
{
  if (frame_length < RTCM3_HEADER_LENGTH + RTCM3_FOOTER_LENGTH) {
    return;
  }

  rtcm3_process_payload(&frame[RTCM3_HEADER_LENGTH], 
                        frame_length - RTCM3_HEADER_LENGTH - RTCM3_FOOTER_LENGTH]);
}
```

Only full messages are passed around via ZMQ. This avoids the need to associate additional metadata (e.g. message type, sender ID, etc.) with ZMQ messages and keeps all ZMQ connections for a given protocol compatible (i.e. no "on the wire" vs "payload only"). 

The data passed to `rtcm3_decode_frame()` comes directly from the incoming ZMQ message. There is no other RTCM-specific decoding in `sbp_rtcm3_bridge`. Framing happens in a separate process.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.0-branch-69-gd897dc7
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-69-gd897dc7/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.0-branch-69-gd897dc7/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.0-branch-69-gd897dc7

**Comment by jacobmcnamee** [comment]
Changes were squashed and merged as part of #167

**Pull request closed without merging**
