### PR TITLE
EX-275: Update gnss_convertors for GLO timestamp fix

### PR DESCRIPTION
**Pull request by nsirola**
Pulls in https://github.com/swift-nav/gnss-converters/pull/102

### CODE REVIEW

**Comment by mfine** [comment]
@nsirola heads up - the interface changed slightly with the converters to provide a context to callbacks:https://github.com/swift-nav/gnss-converters/pull/98. Will need some minor changes to bring it in.

**Comment by nsirola** [comment]
Ok, I'll try to get this to compile locally first and bring the changes into this PR as well.

**Comment by mfine** [comment]
@nsirola should be something like this: https://github.com/swift-nav/piksi_buildroot/compare/master...mfine/gnss-converters-context

```diff
+--- a/package/sbp_rtcm3_bridge/src/sbp.c
+++ b/package/sbp_rtcm3_bridge/src/sbp.c
@@ -84,8 +84,10 @@ settings_ctx_t * sbp_get_settings_ctx(void)
   return ctx.settings_ctx;
 }
 
-void sbp_message_send(u16 msg_type, u8 len, u8 *payload, u16 sender_id)
+void sbp_message_send(u16 msg_type, u8 len, u8 *payload, u16 sender_id, void *context)
 {
+  (void)context;
+
   sbp_tx_ctx_t *tx_ctx = sbp_pubsub_tx_ctx_get(ctx.pubsub_ctx);
   if (tx_ctx == NULL) {
     return;
@@ -109,8 +111,10 @@ void sbp_simulator_enabled_set(bool enabled)
   ctx.simulator_enabled = enabled;
 }
 
-void sbp_base_obs_invalid(double timediff)
+void sbp_base_obs_invalid(double timediff, void *context)
 {
+  (void)context;
+
   if (ctx.simulator_enabled) {
     return;
   }
diff --git a/package/sbp_rtcm3_bridge/src/sbp.h b/package/sbp_rtcm3_bridge/src/sbp.h
index b3d4cb28..5c312f48 100644
--- a/package/sbp_rtcm3_bridge/src/sbp.h
+++ b/package/sbp_rtcm3_bridge/src/sbp.h
@@ -24,10 +24,10 @@ int sbp_init(void);
 void sbp_deinit(void);
 settings_ctx_t * sbp_get_settings_ctx(void);
 pk_loop_t * sbp_get_loop(void);
-void sbp_message_send(u16 msg_type, u8 len, u8 *payload, u16 sender_id);
+void sbp_message_send(u16 msg_type, u8 len, u8 *payload, u16 sender_id, void *context);
 int sbp_callback_register(u16 msg_type, sbp_msg_callback_t cb, void *context);
 void sbp_simulator_enabled_set(bool enabled);
-void sbp_base_obs_invalid(double timediff);
+void sbp_base_obs_invalid(double timediff, void *context);
 int sbp_run(void);
 
 #endif /* SWIFTNAV_SBP_H */
diff --git a/package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c b/package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
index 05462e4e..963f6110 100644
--- a/package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
+++ b/package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
@@ -172,7 +172,7 @@ int main(int argc, char *argv[])
   }
 
   /* Need to init state variable before we get SBP in */
-  rtcm2sbp_init(&state, sbp_message_send, sbp_base_obs_invalid);
+  rtcm2sbp_init(&state, sbp_message_send, sbp_base_obs_invalid, NULL);
 
   if (sbp_init() != 0) {
     piksi_log(LOG_ERR, "error initializing SBP");
```

**Comment by mfine** [comment]
@nsirola not sure - there was an open question about that. But `librtcm` was already similarly submoduled in, and provided in buildroot already:

https://github.com/swift-nav/piksi_buildroot/tree/master/package/librtcm

So not sure how the submodule impacts that. I kind of doubt it has any impact - even though it links against libsbp, I don't think it should pull in any references to sbp code - should just be using headers.

**Comment by nsirola** [comment]
In any case, now both my local build and Travis fail configuring `gnss_convertors 0.3.55` with

```
CMake Error at CMakeLists.txt:11 (add_subdirectory):
  add_subdirectory given source "libsbp/c" which is not an existing
  directory.


CMake Error at CMakeLists.txt:12 (add_subdirectory):
  add_subdirectory given source "librtcm/c" which is not an existing
  directory.
```

**Comment by mfine** [comment]
Ugh. Added those existence checks back in: https://github.com/swift-nav/gnss-converters/pull/103

**Comment by nsirola** [comment]
Thanks, `librtcm` still needed to be updated, but that seems to do it at least in local.

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v1.5.0-develop-2018080320-15-g1256a95d
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=621024)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v1.5.0-develop-2018080320-15-g1256a95d&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v1.5.0-develop-2018080320-15-g1256a95d&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v1.5.0-develop-2018080320-15-g1256a95d
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v1.5.0-develop-2018080320-15-g1256a95d)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.5.0-develop-2018080320-15-g1256a95d/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.5.0-develop-2018080320-15-g1256a95d

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v1.5.0-develop-2018080320-15-g1256a95d
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=621025)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v1.5.0-develop-2018080320-15-g1256a95d&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v1.5.0-develop-2018080320-15-g1256a95d&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v1.5.0-develop-2018080320-15-g1256a95d
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v1.5.0-develop-2018080320-15-g1256a95d)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.5.0-develop-2018080320-15-g1256a95d/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.5.0-develop-2018080320-15-g1256a95d

**Comment by nsirola** [comment]
Works on bench and HITL passes, so merging.

The correct functionality during the first hours of a week to be verified.

**Pull request merged**
