### PR TITLE
Add default whitelist for uart 1 that is compatible with console

### PR DESCRIPTION
**Pull request by denniszollo**

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.1-27-g4262d6b
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.1-27-g4262d6b/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.1-27-g4262d6b/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.1-27-g4262d6b

**Comment by jacobmcnamee** [comment]
Do you want to additionally rename the setting in this PR? https://github.com/swift-nav/piksi_buildroot/blob/51e49f49ea007f5859f42db04a4bb7f9e67fe10d/package/piksi_system_daemon/src/whitelists.c#L151

Also I just want to point out that the new default UART1 whitelist setting will be ~50% of the max setting length.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.2-3-gdeb5a02
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.2-3-gdeb5a02/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.2-3-gdeb5a02/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.2-3-gdeb5a02

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0.2-4-g5eaa27a
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.2-4-g5eaa27a/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.0.2-4-g5eaa27a/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.0.2-4-g5eaa27a

**Pull request closed without merging**
