### PR TITLE
Update readme to reflect current limitations in building from source [DEVC-1186][master]

### PR DESCRIPTION
**Pull request by benjaminaltieri**
Snuck in a command instruction showing the new docker support for `clang-format` too. Can't wait for `clang-tidy` to make it's way in there 😄

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.0.0-develop-2018101616-3-g32f55139
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=727850)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.0.0-develop-2018101616-3-g32f55139&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.0.0-develop-2018101616-3-g32f55139&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.0.0-develop-2018101616-3-g32f55139
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.0.0-develop-2018101616-3-g32f55139)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.0.0-develop-2018101616-3-g32f55139/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.0.0-develop-2018101616-3-g32f55139

**Comment by silverjam** [comment]
This change probably needs to be applied to 2.0 and 2.1

**Comment by benjaminaltieri** [comment]
> This change probably needs to be applied to 2.0 and 2.1

hm, via amend and re-tag? seems straightforward but no idea if this is a no-no w.r.t how release tags are created/managed

**Comment by silverjam** [comment]
@benjaminaltieri I would just do it on the tip of v2.1.0-release and v2.0.0-release, no re-tagging or amending.

**Comment by benjaminaltieri** [comment]
oh, got it. because the default branch shown by GH is what we're after here. easy enough!

**Comment by benjaminaltieri** [comment]
PRs up and ready to :shipit:, last minute thoughts @denniszollo @nicolekelley?

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.0.0-develop-2018101616-12-ge674d03f
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=729117)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.0.0-develop-2018101616-12-ge674d03f&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.0.0-develop-2018101616-12-ge674d03f&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.0.0-develop-2018101616-12-ge674d03f
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.0.0-develop-2018101616-12-ge674d03f)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.0.0-develop-2018101616-12-ge674d03f/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.0.0-develop-2018101616-12-ge674d03f

**Comment by silverjam** [comment]
Killed Travis build for this PR

**Comment by denniszollo** [comment]
Thanks ben for getting some of the hints and tricks into the readme.

I think an explanation of the end build artifacts and the indication of what a successful build will look like upon completion from the make image and docker-make image would be useful.  I suggest we put this in the header for the "building" section before your note about 2.0 to flash back to a Swift image.  In that blurb we could answer the following questions.

- What message indicates build finished without error? 
- Where do the artifacts end up? 
- Which file is which, what is the difference between the uimage and .bin file and DEV file?

**Comment by benjaminaltieri** [comment]
@denniszollo @silverjam are we good with this level of detail around build artifacts and what to do with them?

**Pull request merged**
