### PR TITLE
Cell modem support (master branch)

### PR DESCRIPTION
**Pull request by gsmcmullin**
Master version of #185

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-33-gefea4f2
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-33-gefea4f2/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-33-gefea4f2/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-33-gefea4f2

**Comment by mfine** [comment]
Cherry-picked https://github.com/swift-nav/piksi_buildroot/pull/198 into this PR.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-151-g6d758ad
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-151-g6d758ad/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-151-g6d758ad/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-151-g6d758ad

**Comment by gsmcmullin** [comment]
Also includes #254 for CDMA modem support

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-157-gbfbc0d2
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-157-gbfbc0d2/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-157-gbfbc0d2/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-157-gbfbc0d2

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-branch-201-gca63782
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-201-gca63782/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-branch-201-gca63782/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-branch-201-gca63782

**Pull request merged**
