### PR TITLE
Add current and historical release notes to v2.2.0-release branch

### PR DESCRIPTION
**Pull request by denniszollo**
Per [[HW-271]](https://swift-nav.atlassian.net/browse/HW-271)

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.2.17-2-gcf7c0f74
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=892323)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.17-2-gcf7c0f74&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.17-2-gcf7c0f74&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.2.17-2-gcf7c0f74
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.2.17-2-gcf7c0f74)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.2.17-2-gcf7c0f74/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.2.17-2-gcf7c0f74

**Comment by silverjam** [comment]
@denniszollo @nicolekelley Are we doing this?  Or can we close this?

**Comment by nicolekelley** [comment]
@silverjam - if its ready to go, it would be nice to get this in

**Pull request merged**
