### PR TITLE
Fix Duro cell modem connection after power-on

### PR DESCRIPTION
**Pull request by silverjam**
Fix for piksi_v3_bug_tracking#869

+ Add ifplugd so we can detect when ethernet is actually plugged in and
bring the interface up if it is, otherwise leave the interface down so
we don't hijack any device routes.

+ Enable a few options in pppd to make it a little more robust:
  - defaultroute: tell pppd to add ppp0 as a default route when the
    interface comes up
  - holdoff: time to wait between re-dail attempts
  - lcp-echo-failure: terminate the connection after failing to receive
    N echo requests
  - lcp-echo-interval: how often to send the echo requests above
  - maxfail: how many connection failures will cause pppd to terminate
  - persist: make sure pppd stays resident and always retries

+ Give makefile the ability to support multiple docker buildroots

   Using the following will create a separate volume+container+image
   triplet in order to allow multiple concurrent docker based buildroot
   builds to exist on one host:

   ```
   export DOCKER_SUFFIX=-foo
   make <some-make-rule>
   ```

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017110820-3-ge14ea73
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-3-ge14ea73/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017110820-3-ge14ea73/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-3-ge14ea73

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017110820-8-g063477c
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-8-g063477c/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017110820-8-g063477c/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-8-g063477c

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017110820-9-g07dc14a
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-9-g07dc14a/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017110820-9-g07dc14a/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-9-g07dc14a

**Comment by srossel** [comment]
I have tested this implementation with v1.2.0-develop-2017110820-9-g07dc14a 
The problem is still there. The unit doesn't  connect to NTRIP automatically.
When I tried the workaround, "Disabling" and then "Enabling" NTRIP the unit was not able to connect. Take in consideration I was having connected the Ethernet cable with a static IP to my connect to my computer.

Then I tried again, but disconnecting the ethernet cable. The Swift Console still with  configuration for Ethernet as static.  I hard rebooted the system and still doesn't work. I tried gain the workaround manually disabling and enabling the NTRIP and I cannot cannect anymore. 

I also tried the same scenarios above but with ethernet interface as DHCP (with and without ethernet connected) , Duro still cannot connect to NTRIP automatically.

By checking interfaces with "ifconfig" command, it seems the cell-modem is up and gets connected t the network, although, I cannot ping to google anymore. 

Please, **do not merge** this implementation.  With this built, the interface is broken.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017110820-10-g762b023
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-10-g762b023/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017110820-10-g762b023/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-10-g762b023

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017110820-11-g3e8d7dd
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-11-g3e8d7dd/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017110820-11-g3e8d7dd/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-11-g3e8d7dd

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017110820-12-gccc7c1c
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-12-gccc7c1c/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017110820-12-gccc7c1c/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-12-gccc7c1c

**Comment by srossel** [comment]
Tested with change submitted to v1.2.0-develop-2017110820-11-g3e8d7dd with local built from Jason : https://drive.google.com/drive/folders/1jgD2CUaV_tdpms3jkt6R9b_KlY3wIQqO

Scenario # 1 :
- Cell modem enabled.
- Ethernet cable no connected to local network (Interface configured with static IP) 
Results:
-After hard reboot, Duro will start and will take ~105 [seconds] to get into Fix RTK Mode.
Observations:
- From Float RTK to Fix RTK takes long time. I observed the Base latency is about 800[ms]and very intermittent(reporting "--" value). Once Duro gets into Fix RTK the latency goes down to 350 [ms]

Scenario # 2 :
- Cell modem enabled.
- Ethernet cable connected to local network (Interface configured with static IP 192.168.1.102) 
Results:
-After hard reboot, Duro will start and will take  ~104 [seconds] to get into Fix RTK  Mode.
- I was able to connect via ssh from my computer to Duro via this local network configured while Duro  was receiving corrections from Cell Modem.
Observations:
- From Float RTK to Fix RTK takes long time. I observed the Base latency is around 800[ms] and very intermittent(reporting "--" value). Once Duro gets into Fix RTK the latency goes down to 350 [ms].

Scenario # 3 :
- Cell modem enabled.
- Ethernet cable connected to public network (DHCP)
Results:
-After hard reboot, Duro will start and will take  ~77 [seconds] to get into Fix RTK Mode.
- I was able to connect via ssh from my computer to Duro though the public network.
Observations:
- From Float RTK to Fix RTK did not take long time. I observed the Base latency moving between 350[ms] and 600[ms]. The Base Latency is been reported constantly on Swift Console. 


Scenario # 4 :
- Cell modem disabled.
- Ethernet cable connected to public network (DHCP)
Results:
-After hard reboot, Duro will start and will take  ~73 [seconds] to get into Fix RTK Mode.
Observations:
- From Float RTK to Fix RTK took at least 10-15[s]. I observed the Base latency stays very stable around 590[ms]. 

Summary: 
- The implementation seems to do what is expected, based on the scenarios that I mentioned above.
- I would like to know if we have some room for improving the connection time and reducing base latency while moving from Float RTK to Fix RTK while using Cell-modem only as configuration. 
- We will require to run GTT test and drive with this implementation.

Thank you very much @silverjam for this implementation 🥇 . Let's now try to polish it if possible.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017110820-13-g25f10f0
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-13-g25f10f0/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017110820-13-g25f10f0/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-13-g25f10f0

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017110820-14-ga70efbc
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-14-ga70efbc/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017110820-14-ga70efbc/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017110820-14-ga70efbc

**Comment by srossel** [comment]
This issue is duplicated from:

https://github.com/swift-nav/piksi_v3_bug_tracking/issues/869

We are running 75C Soak test for the next 24hrs. We need to test the cell-modem since it is supposed to be shipped on v1.3.
For now, it is still ship-blocker and I will update this issue as we progress with our testing.

**Comment by srossel** [comment]
Test ,"75C Soak" was successfully completed.
We are currently running the following tests : 
-40C continuous operation.
-40C on-off
With Cell Modem. 
Test should be completed by 11/22/17 by mid-day. so far so good. I will keep everybody updated on the tests results once we get them done. 

Thanks!

**Pull request merged**
