### PR TITLE
Handle EINTR on the reads and writes

### PR DESCRIPTION
**Pull request by mfine**
Look for EINTR on reads and writes from the pipes.

/cc @jacobmcnamee

### CODE REVIEW

**Comment by jacobmcnamee** [comment]
You shouldn't need to explicitly handle any signals, but I'd check to make sure curl isn't doing anything strange. E.g. czmq by default handles a couple signals and only sets a variable indicating that the program should be terminated, meaning that those infinite loops checking for EINTR might cause problems.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.10-6-ga949d8b
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.10-6-ga949d8b/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.10-6-ga949d8b/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.10-6-ga949d8b

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.13-4-g2b380da
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.13-4-g2b380da/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.13-4-g2b380da/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.13-4-g2b380da

**Comment by mfine** [comment]
Replaced by https://github.com/swift-nav/piksi_buildroot/pull/235.

**Pull request closed without merging**
