### PR TITLE
piksi_leds: Show white LEDs until firmware is running

### PR DESCRIPTION
**Pull request by gsmcmullin**

### CODE REVIEW

**Comment by gsmcmullin** [comment]
@axlan I think white is better than their normal colours:
- If the firmware fails to finish the boot sequence, this is clear form the LEDs, rather than being confused with their normal meanings
- For QA you can tell if all the colours are working

Is there a certain minimum time you want them in this state?  `piksi_leds` is only started quite late in the boot process

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017111721-15-g7f9f352
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017111721-15-g7f9f352/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017111721-15-g7f9f352/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017111721-15-g7f9f352

**Comment by gsmcmullin** [comment]
PR to add new write response message https://github.com/swift-nav/libsbp/pull/525

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017112220-3-g8f5b54f
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017112220-3-g8f5b54f/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017112220-3-g8f5b54f/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017112220-3-g8f5b54f

**Pull request merged**
