### PR TITLE
Implement SBP settings write response

### PR DESCRIPTION
**Pull request by gsmcmullin**
Before merging:
- [x] Update libsbp reference once https://github.com/swift-nav/libsbp/pull/525 is merged
- [x] Update firmware to send new response
- [x] Test with malformed settings messages

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017112220-3-g8e9e421
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017112220-3-g8e9e421/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017112220-3-g8e9e421/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017112220-3-g8e9e421

**Comment by silverjam** [comment]
@anth-cole A new libsbp release should get cut for this PR, which should allow us to merge https://github.com/swift-nav/piksi_buildroot/pull/394 after this PR is merged.

**Comment by mfine** [comment]
@silverjam I cut a tag for the glo biases message yesterday https://github.com/swift-nav/libsbp/tree/v2.3.1

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017112220-11-g44dd453
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017112220-11-g44dd453/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017112220-11-g44dd453/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017112220-11-g44dd453

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017112220-11-gd544dad
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017112220-11-gd544dad/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017112220-11-gd544dad/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017112220-11-gd544dad

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2017113000-5-gba5ef5b
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017113000-5-gba5ef5b/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2017113000-5-gba5ef5b/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2017113000-5-gba5ef5b

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2.0-develop-2018010520-14-g40a2ade
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2018010520-14-g40a2ade/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.2.0-develop-2018010520-14-g40a2ade/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.2.0-develop-2018010520-14-g40a2ade

**Pull request merged**
