### PR TITLE
SD card workaround FPGA reconfiguration

### PR DESCRIPTION
**Pull request by gsmcmullin**
Fix for https://github.com/swift-nav/piksi_v3_bug_tracking/issues/604

- MMC driver is build as a module
- DEV configuration will load module, wait for mount, copy images, and then remove the module
- FPGA is configured by the kernel before the driver is loaded to avoid an unpredictable hardware state
- The module is loaded and automounted at the end of the boot process

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-develop-2017082521-4-g8f315a9
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017082521-4-g8f315a9/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-develop-2017082521-4-g8f315a9/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017082521-4-g8f315a9

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-develop-2017082521-4-gde1ef6f
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017082521-4-gde1ef6f/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-develop-2017082521-4-gde1ef6f/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017082521-4-gde1ef6f

**Comment by lbara** [comment]
I tested it and it works fine. I'm merging it now.

**Comment by srossel** [comment]
Two weeks ago I tried PiksiMulti-v1.1.0-develop-2017090622.bin firmware on Piksi Multi Dev Kit and the SDcard pop up properly.
Now, with 1.2.2 firmware SDCard is not working (It has been properly plugged). I tried with two different SDCards. Here are some screenshots.

image

image

Any thoughts ?

**Comment by srossel** [comment]
Please, let's review again this PR. with the firmware build PiksiMulti-v1.1.0-develop-2017090622.bin I am able to see the SDCard. With the current 1.2.2 the SDCard doesn't come up.

Here some screenshots:

image

image

**Comment by silverjam** [comment]
@srossel Remind me tomorrow and I'll take a look at this

**Comment by silverjam** [comment]
Seems if I have an sdcard inserted when booting (with firmware on it) it prevents the system from hotplugging/detecting the card later.  If I boot up the system w/o the sdcard inserted, then insert it later, it works.

Also seeing this during boot-up:
```
modprobe: invalid option -- 'a'
```

**Pull request merged**
