### PR TITLE
Fix piksi_multitool upgrade path for removal of fio_ex user [DEVC-1121] [release]

### PR DESCRIPTION
**Pull request by silverjam**
Correct spawn_nc for rename of fio_ex -> fileio [DEVC-1121].

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v2.1.7-2-g13cb3c70
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=701658)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.1.7-2-g13cb3c70&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.1.7-2-g13cb3c70&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v2.1.7-2-g13cb3c70
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v2.1.7-2-g13cb3c70)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v2.1.7-2-g13cb3c70/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v2.1.7-2-g13cb3c70

**Comment by silverjam** [comment]
@yizow just realized the test case you're working on (the "new" version with piksi_multitool will fail because of this bug) so you're the perfect person to review this PR 😊

**Comment by yizow** [comment]
`fio_ex` occurs in two additional files:
```
package/sbp_fileio_daemon/sbp_fileio_daemon.mk
15:	fio_ex -1 fio_ex -1 * - - -

board/piksiv3/rootfs-overlay/etc/init.d/S81sbp_fileio_daemon_external
8:user="fio_ex"
```

Do Those need to be changed as well?

**Comment by silverjam** [comment]
@yizow is that in v2.1.0-release branch? I thought I already found all occurances, the S81sbp_fileio_external and S81sbp_fileio_firmware scripts should both be using the "fileio" user.

**Comment by yizow** [comment]
Oops, my bad, i was on 2.0.0 release

**Comment by silverjam** [comment]
@yizow generally the author will merge (unless there are extenuating circumstances)-- for this PR, can you download the firmware image and make sure the upgrade (with `piksi_multitool`) works?  You'll have to upgrade to this firmware with another method (like ssh, or usb), but after that you should be able to use `piksi_multitool` to upgrade from this PR firmware to another firmware.

**Pull request merged**
