### PR TITLE
Revert enable pfw welcome [DEVC-1012] [master]

### PR DESCRIPTION
**Pull request by benjaminaltieri**
To avoid any hang that this package can cause in the short term, disable this utility until we are sure it will not block boot in all cases.

### CODE REVIEW

**Comment by denniszollo** [comment]
To be complete shouldn't we remove the package "https://github.com/swift-nav/piksi_buildroot/tree/25cfa36458ea300f62c3607ca09c6e0c437f998b/package/pfw_welcome" as well? 

Here we removed the init but left the code; if that is what we want to do we should probably put a big comment in that about what we plan to do with pfw_welcome and what needs to change to re-enable it.

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v1.5.0-develop-2018080320-3-gd0a1a4f2
There was an error using the HITL API to kick off smoke tests for this commit. See https://travis-ci.org/swift-nav/piksi_buildroot/builds/412811832.

**Comment by anonymous-travis-swiftnav** [comment]
## HITL smoke tests: v1.5.0-develop-2018080320-3-gd0a1a4f2
These test runs are kicked off whenever you push a new commit to this PR. All passfail metrics in these runs must pass for the `hitl/pass-fail` status to be marked successful.
### job status
+ [live-roof-650-townsend-post runs](https://gnss-analysis.swiftnav.com/jobs/id=617463)
### gnss-analysis results
At least one run must complete for these links to have data.
#### passfail
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v1.5.0-develop-2018080320-3-gd0a1a4f2&groupby_key=firmware&display_type=table)
#### detailed
+ [live-roof-650-townsend-post](https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=detailed&scenario=live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v1.5.0-develop-2018080320-3-gd0a1a4f2&groupby_key=firmware&display_type=table)

**Comment by anonymous-travis-swiftnav** [comment]
## v1.5.0-develop-2018080320-3-gd0a1a4f2
+ [Artifacts (HITL Dashboard Page)](https://gnss-analysis.swiftnav.com/artifacts/build_type=buildroot_pr&name_filter=v1.5.0-develop-2018080320-3-gd0a1a4f2)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.5.0-develop-2018080320-3-gd0a1a4f2/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.5.0-develop-2018080320-3-gd0a1a4f2

**Pull request merged**
