### PR TITLE
Upload limits

### PR DESCRIPTION
**Pull request by mfine**
Limit traffic being uploaded to Skylark. Previously, all traffic from the device had been heading to Skylark :( Now only LLH positions and heartbeats are uploaded. Additionally, these are rate limited by the filters.

/cc @jacobmcnamee @denniszollo

### CODE REVIEW

**Comment by cbeighley** [comment]
@mfine Don't you want to upload obs and maybe ephemerides?

**Comment by cbeighley** [comment]
Ah this is a workaround for the time being for the broker hammering?

**Comment by mfine** [comment]
@cbeighley yeah, we'd like to eventually get obs and ephemeris and others up to the broker - but currently we're not using any of them. We'll definitely bring them in, but for now we should leave them out.

**Comment by cbeighley** [comment]
👍

**Pull request merged**
