### PR TITLE
libnetwork + robustness + handling stalled connections.

### PR DESCRIPTION
**Pull request by mfine**
Consolidate to a single networking library, libnetwork.
Add robustness handling around pipe reading and writing.
Prevent stalled connections.

Fixes https://github.com/swift-nav/skylark-bug-tracking/issues/17.

/cc @jacobmcnamee

### CODE REVIEW

**Comment by mfine** [comment]
Also added `strace` package.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.13-6-gcc8a4f6
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.13-6-gcc8a4f6/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.13-6-gcc8a4f6/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.13-6-gcc8a4f6

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.14-3-gd0cb055
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.14-3-gd0cb055/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.14-3-gd0cb055/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.14-3-gd0cb055

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.14-3-g01318b8
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.14-3-g01318b8/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.14-3-g01318b8/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.14-3-g01318b8

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.14-4-gc3b98c5
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.14-4-gc3b98c5/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.14-4-gc3b98c5/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.14-4-gc3b98c5

**Pull request merged**
