### PR TITLE
[DO NOT MERGE] Update to Linux xilinx-v2017.3 tag

### PR DESCRIPTION
**Pull request by silverjam**
Update to Xilinx Linux tag `xilinx-v2017.3` and port our patches and driver (rpmsg_piksi).

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.1.0-develop-2017100621-19-g21d268a
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017100621-19-g21d268a/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.1.0-develop-2017100621-19-g21d268a/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.1.0-develop-2017100621-19-g21d268a

**Comment by silverjam** [comment]
Updated rpmsg_piksi according to the changes here:
- https://github.com/Xilinx/linux-xlnx/blob/xilinx-v2017.3/include/linux/rpmsg.h
- And here:
  - https://patchwork.kernel.org/patch/9309879/
  - https://patchwork.kernel.org/patch/9310017/
  - https://patchwork.kernel.org/patch/9309905/
  - https://patchwork.kernel.org/project/LKML/list/?submitter=155101&page=3

**Comment by anonymous-travis-swiftnav** [comment]
## v1.3.0-develop-2018020221-4-g9ac727a
+ [Artifacts (HITL Dashboard Page)](http://hitl-dashboard.swiftnav.com/files/swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018020221-4-g9ac727a/)
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=swiftnav-artifacts-pull-requests&prefix=piksi_buildroot/v1.3.0-develop-2018020221-4-g9ac727a/)
+ s3://swiftnav-artifacts-pull-requests/piksi_buildroot/v1.3.0-develop-2018020221-4-g9ac727a

**Comment by silverjam** [comment]
Trying this out in case random Windows USB issues were just a Linux bug, but this branch doesn't really boot yet.  There are several obvious things that are broken:

+ remoteproc doesn't yet load the rtos, rpmsg_piksi has been upated and compiles, but remoteproc is having issues starting and it's unclear what's going wrong (no logging / errors) remoteproc just stalls when you explicitly request a start (according to http://www.wiki.xilinx.com/OpenAMP+2017.1#Additional%20examples:-ZynqMP%20Linux%20Master%20running%20on%20APU%20Linux%20loads%20arbitrary%20RPU%20Firmware) you can do the following: `echo start > /sys/class/remoteproc/remoteproc0/state` -- however this command just hangs.

+ `upgrade_tool` appears broken once you update to this firmware, it will stop after writing around 88% of the flash and exit with an error (errno says "bad address"), no obvious logs / errors from the kernel.

**Comment by silverjam** [comment]
Another issue: the TTYs attached to the USB gadget are not responsive to text input.

**Pull request closed without merging**
